# Generated by Django 4.2.8 on 2024-02-08 13:48

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import api_app.visualizers_manager.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_app", "0001_1_initial_squashed"),
        ("playbooks_manager", "0001_initial_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualizerConfig",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\w+$",
                                "Your name should match the [A-Za-z0-9_] characters",
                            )
                        ],
                    ),
                ),
                (
                    "python_module",
                    models.ForeignKey(
                        limit_choices_to={
                            "base_path": "api_app.visualizers_manager.visualizers"
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="api_app.pythonmodule",
                    ),
                ),
                ("description", models.TextField()),
                ("disabled", models.BooleanField(default=False)),
                (
                    "playbooks",
                    models.ManyToManyField(
                        "playbooks_manager.playbookconfig",
                        related_name="visualizers",
                    ),
                ),
                (
                    "disabled_in_organizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(app_label)s_%(class)s_disabled",
                        to="certego_saas_organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VisualizerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameters", models.JSONField(default={}, editable=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="visualizers_manager.visualizerconfig",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("KILLED", "Killed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "report",
                    models.JSONField(
                        default=list,
                        validators=[
                            api_app.visualizers_manager.validators.validate_report
                        ],
                    ),
                ),
                (
                    "errors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("task_id", models.UUIDField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="api_app.job",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="visualizerconfig",
            index=models.Index(
                fields=["python_module", "disabled"],
                name="visualizers_python__2c4ded_idx",
            ),
        ),
        migrations.AlterModelOptions(
            name="visualizerreport",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="visualizerconfig",
            options={"ordering": ["name", "disabled"]},
        ),
        migrations.RenameIndex(
            model_name="visualizerconfig",
            new_name="visualizers_python__8b1832_idx",
            old_name="visualizers_python__2c4ded_idx",
        ),
        migrations.AddField(
            model_name="visualizerconfig",
            name="health_check_status",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name="visualizerconfig",
            name="health_check_task",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="healthcheck_for_%(class)s",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="visualizerconfig",
            name="routing_key",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AddField(
            model_name="visualizerconfig",
            name="soft_time_limit",
            field=models.IntegerField(
                default=60, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="visualizerreport",
            name="sent_to_bi",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="visualizerconfig",
            name="python_module",
            field=models.ForeignKey(
                limit_choices_to={
                    "base_path__in": ["api_app.visualizers_manager.visualizers"]
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api_app.pythonmodule",
            ),
        ),
        migrations.AlterField(
            model_name="visualizerreport",
            name="parameters",
            field=models.JSONField(editable=False),
        ),
        migrations.AddIndex(
            model_name="visualizerreport",
            index=models.Index(
                fields=["sent_to_bi", "-start_time"], name="visualizerreportsBISearch"
            ),
        ),
    ]
