# Generated by Django 4.2.8 on 2024-02-08 13:48

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import api_app.defaults
import api_app.validators
import api_app.visualizers_manager.validators

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# api_app.visualizers_manager.migrations.00011_dns_visualizer
# api_app.visualizers_manager.migrations.0002_datamigration
# api_app.visualizers_manager.migrations.0005_visualizerconfig_disabled_in_org
# api_app.visualizers_manager.migrations.0007_auto_20230308_1623
# api_app.visualizers_manager.migrations.0008_parent_playbook_foreign_key
# api_app.visualizers_manager.migrations.0009_remove_parent_playbook
# api_app.visualizers_manager.migrations.0013_params
# api_app.visualizers_manager.migrations.0018_visualizer_config
# api_app.visualizers_manager.migrations.0019_dns_visualizer_change
# api_app.visualizers_manager.migrations.0020_visualizer_config
# api_app.visualizers_manager.migrations.0022_remove_visualizerconfig_analyzers_and_more


class Migration(migrations.Migration):
    replaces = [
        ("visualizers_manager", "0001_initial"),
        ("visualizers_manager", "0002_datamigration"),
        ("visualizers_manager", "0003_auto_20230301_1415"),
        ("visualizers_manager", "0004_alter_visualizerreport_report"),
        ("visualizers_manager", "0005_visualizerconfig_disabled_in_org"),
        ("visualizers_manager", "0006_alter_visualizerreport_job"),
        ("visualizers_manager", "0007_auto_20230308_1623"),
        ("visualizers_manager", "0008_parent_playbook_foreign_key"),
        ("visualizers_manager", "0009_remove_parent_playbook"),
        ("visualizers_manager", "00010_remove_runtime_configuration"),
        ("visualizers_manager", "00011_dns_visualizer"),
        (
            "visualizers_manager",
            "0012_alter_visualizerconfig_disabled_in_organizations_and_more",
        ),
        ("visualizers_manager", "0013_params"),
        ("visualizers_manager", "0014_alter_visualizerreport_report"),
        ("visualizers_manager", "0015_alter_visualizerreport_unique_together"),
        ("visualizers_manager", "0016_visualizerreport_name"),
        ("visualizers_manager", "0017_alter_visualizerreport_options"),
        ("visualizers_manager", "0018_visualizer_config"),
        ("visualizers_manager", "0019_dns_visualizer_change"),
        ("visualizers_manager", "0020_visualizer_config"),
        ("visualizers_manager", "0021_alter_visualizerconfig_options"),
        ("visualizers_manager", "0022_remove_visualizerconfig_analyzers_and_more"),
    ]

    dependencies = [
        ("api_app", "0001_1_initial_squashed"),
        ("playbooks_manager", "0001_initial_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualizerConfig",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\w+$",
                                "Your name should match the [A-Za-z0-9_] characters",
                            )
                        ],
                    ),
                ),
                (
                    "python_module",
                    models.ForeignKey(
                        limit_choices_to={
                            "base_path": "api_app.visualizers_manager.visualizers"
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="api_app.pythonmodule",
                    ),
                ),
                ("description", models.TextField()),
                ("disabled", models.BooleanField(default=False)),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizers",
                        to="playbooks_manager.playbookconfig",
                    ),
                ),
                (
                    "disabled_in_organizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(app_label)s_%(class)s_disabled",
                        to="certego_saas_organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VisualizerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="visualizers_manager.visualizerconfig",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("KILLED", "Killed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "report",
                    models.JSONField(
                        default=list,
                        validators=[
                            api_app.visualizers_manager.validators.validate_report
                        ],
                    ),
                ),
                (
                    "errors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("task_id", models.UUIDField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="api_app.job",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="visualizerconfig",
            index=models.Index(
                fields=["python_module", "disabled"],
                name="visualizers_python__2c4ded_idx",
            ),
        ),
        migrations.AlterModelOptions(
            name="visualizerreport",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="visualizerconfig",
            options={"ordering": ["name", "disabled"]},
        ),
    ]
