# Generated by Django 3.2.18 on 2023-03-06 08:12

import api_app.visualizers_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizers_manager', '0003_auto_20230301_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizerreport',
            name='report',
            field=models.JSONField(default=dict, validators=[api_app.visualizers_manager.validators.validate_report]),
        ),
    ]
