# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-03-08 16:23

import django.db.models.deletion
from django.db import migrations, models


def migrate(apps, schema_editor):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    VisualizerReport = apps.get_model("visualizers_manager", "VisualizerReport")
    for report in VisualizerReport.objects.all():
        report.config = VisualizerConfig.objects.get(name=report.name)
        report.save()

def backwards_migrate(apps, schema_editor):
    VisualizerReport = apps.get_model("visualizers_manager", "VisualizerReport")
    for report in VisualizerReport.objects.all():
        report.name = report.config.name
        report.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_mitm_configs'),
        ('visualizers_manager', '0006_alter_visualizerreport_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizerreport',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='visualizers_manager.visualizerconfig'),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate, backwards_migrate
        ),
        migrations.AlterField(
            model_name='visualizerreport',
            name="config",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports',
                                    to='visualizers_manager.visualizerconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='visualizerreport',
            unique_together={('config', 'job')},
        ),

        migrations.RemoveField(
            model_name='visualizerreport',
            name='name',
        ),
    ]
