# Generated by Django 4.1.7 on 2023-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizers_manager', '0015_alter_visualizerreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizerreport',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
