# Generated by Django 4.1.9 on 2023-05-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualizers_manager", "0017_dns_visualizer_change"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visualizerreport",
            options={"ordering": ["pk"]},
        ),
    ]
