# Generated by Django 4.1.9 on 2023-05-23 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0020_visualizer_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visualizerconfig",
            options={"ordering": ["name", "disabled"]},
        ),
    ]
