# Generated by Django 4.1.9 on 2023-06-22 07:07

from django.db import migrations, models


def _migrate_dns(apps):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    visualizer = VisualizerConfig.objects.get(name="DNS")
    visualizer.playbooks.set([PlaybookConfig.objects.get(name="Dns")])
    visualizer.full_clean()
    visualizer.save()


def _reverse_migrate_dns(apps):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    visualizer = VisualizerConfig.objects.get(name="DNS")
    visualizer.analyzers.set([
        AnalyzerConfig.objects.get(name="Classic_DNS"),
        AnalyzerConfig.objects.get(name="CloudFlare_DNS"),
        AnalyzerConfig.objects.get(name="DNS0_EU"),
        AnalyzerConfig.objects.get(name="Google_DNS"),
        AnalyzerConfig.objects.get(name="Quad9_DNS"),
        AnalyzerConfig.objects.get(name="CloudFlare_Malicious_Detector"),
        AnalyzerConfig.objects.get(name="DNS0_EU_Malicious_Detector"),
        AnalyzerConfig.objects.get(name="Quad9_Malicious_Detector"),
    ])
    visualizer.full_clean()
    visualizer.save()


def _migrate_yara(apps):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    visualizer = VisualizerConfig.objects.get(name="Yara")
    visualizer.playbooks.set([PlaybookConfig.objects.get(name="Sample_Static_Analysis")])
    visualizer.full_clean()
    visualizer.save()

def _reverse_migrate_yara(apps):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    visualizer = VisualizerConfig.objects.get(name="Yara")
    visualizer.analyzers.set([
        AnalyzerConfig.objects.get(name="Yara"),
    ])
    visualizer.full_clean()
    visualizer.save()

def migrate(apps, schema_editor):
    _migrate_yara(apps)
    _migrate_dns(apps)

def reverse_migrate(apps, schema_editor):
    _reverse_migrate_yara(apps)
    _reverse_migrate_dns(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_manager', '0015_alter_playbookconfig_options'),
        ('visualizers_manager', '0021_alter_visualizerconfig_options'),
        ('analyzers_manager', '0030_alter_analyzerconfig_options'),
        ('connectors_manager', '0017_alter_connectorconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizerconfig',
            name='playbooks',
            field=models.ManyToManyField(related_name='visualizers', to='playbooks_manager.playbookconfig'),
        ),
        migrations.RunPython(migrate, reverse_migrate),
        migrations.RemoveField(
            model_name='visualizerconfig',
            name='analyzers',
        ),
        migrations.RemoveField(
            model_name='visualizerconfig',
            name='connectors',
        ),
    ]
