# Generated by Django 4.1.10 on 2023-08-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0039_remove_fields"),
        ("visualizers_manager", "0025_alter_python_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualizerconfig",
            name="python_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api_app.pythonmodule",
            ),
        ),
    ]
