# Generated by Django 4.1.10 on 2023-10-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0049_remove_pluginconfig_api_app_plu_owner_i_691c79_idx_and_more"),
        ("visualizers_manager", "0027_visualizerconfig_routing_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualizerconfig",
            name="python_module",
            field=models.ForeignKey(
                limit_choices_to={
                    "base_path__in": ["api_app.visualizers_manager.visualizers"]
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api_app.pythonmodule",
            ),
        ),
    ]
