# Generated by Django 4.1.10 on 2023-10-23 13:47

from django.db import migrations, models


def migrate(apps, schema_editor):
    Visualizer = apps.get_model("visualizers_manager", "VisualizerConfig")
    for visualizer in Visualizer.objects.all():
        visualizer.playbooks.set([visualizer.playbook])
        visualizer.save()


def reverse_migrate(apps, schema_editor):
    ...


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0021_alter_playbookconfig_name_and_more"),
        ("visualizers_manager", "0028_alter_visualizerconfig_python_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualizerconfig",
            name="playbooks",
            field=models.ManyToManyField(
                related_name="visualizers", to="playbooks_manager.playbookconfig"
            ),
        ),
        migrations.RunPython(migrate, reverse_migrate),
        migrations.RemoveField(
            model_name="visualizerconfig",
            name="playbook",
        ),
    ]
