# Generated by Django 4.1.10 on 2023-12-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0032_visualizerconfig_health_check_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualizerreport",
            name="parameters",
            field=models.JSONField(default={}, editable=False),
            preserve_default=False,
        ),
    ]
