# Generated by Django 4.2.8 on 2023-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0033_visualizerreport_parameters"),
        ("playbooks_manager", "0022_add_dns0_to_free_playbook"),
        ("pivots_manager", "0022_pivotreport_pivotreportsbisearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualizerreport",
            name="sent_to_bi",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
