# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_2_change_primary_key"),
        ("api_app", "0057_2_change_primary_key"),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "visualizers_manager_visualizerconfig" DROP CONSTRAINT "visualizers_manager_visualizerconfig_pkey" CASCADE;'
        ),
        migrations.AlterField(
            model_name="visualizerconfig",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                primary_key=False,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$", "Your name should match the [A-Za-z0-9_] characters"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="visualizerconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, serialize=False, verbose_name="ID", primary_key=True
            ),
        ),
    ]
