# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_1_change_primary_key"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualizerreport",
            name = "config",
            field=models.CharField(
                max_length=100,
                null=False,
                blank=False
            )
        ),
    ]
