# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models


def migrate(apps, schema_editor):
    VisualizerReport = apps.get_model("visualizers_manager", "VisualizerReport")
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    name = VisualizerConfig.objects.filter(name=models.OuterRef("old_config")).values_list("pk")[:1]
    VisualizerReport.objects.update(
        config=models.Subquery(name)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_3_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visualizerreport",
            old_name="config",
            new_name="old_config"
        ),
        migrations.AddField(
            model_name="visualizerreport",
            name="config",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="visualizers_manager.visualizerconfig",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate
        ),
        migrations.RemoveField(
            model_name="visualizerreport",
            name="old_config"
        )
    ]
