# Generated by Django 4.2.8 on 2024-01-09 14:31
import django
from django.contrib.postgres.expressions import ArraySubquery
from django.db import migrations, models


def migrate(apps, schema_editor):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    VisualizerConfig.objects.update(
        playbooks2=ArraySubquery(
            VisualizerConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "playbooks__name"
            )
        ),
        disabled2=ArraySubquery(
            VisualizerConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "disabled_in_organizations__pk"
            )
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_1_change_primary_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualizerreport",
            name="config",
            field=models.CharField(max_length=100, null=False, blank=False),
        ),
        migrations.AddField(
            model_name="visualizerconfig",
            name="playbooks2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="visualizerconfig",
            name="disabled2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(model_name="visualizerconfig", name="playbooks"),
        migrations.RemoveField(
            model_name="visualizerconfig", name="disabled_in_organizations"
        ),
    ]
