# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0035_visualizerreport_visualizerreportsbisearch"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = []
