# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0002_0004_visualizer_config_yara"),
        ("api_app", "0001_2_initial_squashed"),
    ]

    operations = []
