# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations, models


def migrate(apps, schema_editor):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    id = 1
    for config in VisualizerConfig.objects.all():
        config.id = id
        config.save()
        id += 1


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0035_visualizerreport_visualizerreportsbisearch"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualizerconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.AlterField(
            model_name="visualizerconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
            ),
        ),
    ]
