# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.contrib.postgres.fields
from django.contrib.postgres.expressions import ArraySubquery
from django.db import migrations, models


def migrate(apps, schema_editor):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    VisualizerConfig.objects.update(
        playbooks2=ArraySubquery(
            VisualizerConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "playbooks__name"
            )
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0024_1_change_primary_key"),
        ("visualizers_manager", "0036_4_change_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualizerconfig",
            name="playbooks2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(model_name="visualizerconfig", name="playbooks"),
    ]
