# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations, models


def migrate(apps, schema_editor):
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    for config in VisualizerConfig.objects.all():
        playbooks = PlaybookConfig.objects.filter(name__in=config.playbooks2)
        config.playbooks.set(playbooks.values_list("pk", flat=True))


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0024_3_change_primary_key"),
        ("visualizers_manager", "0037_2_change_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualizerconfig",
            name="playbooks",
            field=models.ManyToManyField(
                related_name="visualizers",
                to="playbooks_manager.PlaybookConfig",
            ),
        ),
        migrations.RunPython(
            migrate,
        ),
        migrations.RemoveField(model_name="visualizerconfig", name="playbooks2"),
    ]
