# All additional integrations should be added following this format only.

services:
  nuclei_analyzer:
    image: pranjalg1310/nuclei-analyzer:1.2.2
    container_name: nuclei_analyzer
    restart: unless-stopped
    expose:
      - "4008"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intel_owl
    depends_on:
      - uwsgi
