location = /favicon.ico {
    access_log off; 
    log_not_found off; 
}

location /hc {
    return 200;
}

# All requests to the Django/Gunicorn server.
location / {
    root /;
    proxy_pass                  http://django;
    proxy_set_header            Host $http_host;
    proxy_set_header            X-Real-IP $remote_addr;
    proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header            X-Forwarded-Proto $scheme;
    proxy_set_header            X-Forwarded-Host $host;
    proxy_redirect              off;
    proxy_read_timeout          600;
    client_max_body_size        100m;
}


# rate limiting for django admin panel
location ^~/admin {
    limit_req zone=adminlimit;

    proxy_pass                  http://django;
    proxy_set_header            Host $http_host;
    proxy_set_header            X-Real-IP $remote_addr;
    proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header            X-Forwarded-Proto $scheme;
    proxy_set_header            X-Forwarded-Host $host;
    proxy_redirect              off;
    proxy_read_timeout          600;
    client_max_body_size        100m;
}

# Websocket 
include websocket.conf;
