# Generated by Django 3.1.3 on 2020-12-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_factor", "0006_phonedevice_key_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonedevice",
            name="throttling_failure_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of successive failed attempts."
            ),
        ),
        migrations.AddField(
            model_name="phonedevice",
            name="throttling_failure_timestamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="A timestamp of the last failed verification attempt.\
                           Null if last attempt succeeded.",
                null=True,
            ),
        ),
    ]
