# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

from api_app.ingestors_manager.models import IngestorConfig
from certego_saas.apps.organization.organization import Membership, Organization
from tests import CustomViewSetTestCase
from tests.api_app.test_views import AbstractConfigViewSetTestCaseMixin


class IngestorConfigViewSetTestCase(
    AbstractConfigViewSetTestCaseMixin, CustomViewSetTestCase
):
    URL = "/api/ingestor"

    @classmethod
    @property
    def model_class(cls) -> IngestorConfig:
        return IngestorConfig

    def test_organization_disable(self):
        org, _ = Organization.objects.get_or_create(name="test")
        Membership.objects.get_or_create(
            user=self.user, organization=org, is_owner=False
        )
        response = self.client.post(f"{self.URL}/GreedyBear/organization")
        self.assertEqual(response.status_code, 404)

    def test_organization_enable(self):
        org, _ = Organization.objects.get_or_create(name="test")
        Membership.objects.get_or_create(
            user=self.user, organization=org, is_owner=False
        )
        response = self.client.delete(f"{self.URL}/GreedyBear/organization")
        self.assertEqual(response.status_code, 404)

    def test_get(self):
        # 1 - existing ingestor
        self.client.force_authenticate(user=self.user)
        response = self.client.get(f"{self.URL}/GreedyBear")
        self.assertEqual(response.status_code, 200, response.content)
        self.assertEqual(
            response.json(),
            {
                "config": {"queue": "default", "soft_time_limit": 60},
                "delay": "00:00:00",
                "description": "Queries feeds which are generated by the [GreedyBear "
                "Project](https://intelowlproject.github.io/docs/GreedyBear/Introduction/).",
                "disabled": True,
                "health_check_status": True,
                "health_check_task": None,
                "id": 4,
                "maximum_jobs": 50,
                "name": "GreedyBear",
                "playbooks_choice": ["Popular_IP_Reputation_Services"],
                "python_module": 215,
                "routing_key": "ingestor",
                "schedule": {
                    "day_of_month": "*",
                    "day_of_week": "*",
                    "hour": "0",
                    "minute": "0",
                    "month_of_year": "*",
                },
                "soft_time_limit": 60,
            },
        )
        # 2 - missing ingestor
        response = self.client.get(f"{self.URL}/non_existing")
        self.assertEqual(response.status_code, 404, response.content)
        result = response.json()
        self.assertEqual(
            result, {"detail": "No IngestorConfig matches the given query."}
        )

    def test_get_config(self):
        # 1 - existing ingestor
        self.client.force_authenticate(user=self.user)
        response = self.client.get(f"{self.URL}/GreedyBear/plugin_config")
        self.assertEqual(response.status_code, 200, response.content)
        result = response.json()
        # auto filled by the model and hard to mock
        for user_config in result["user_config"]:
            user_config.pop("updated_at", "")
        self.assertEqual(
            result,
            {
                "organization_config": [],
                "user_config": [
                    {
                        "analyzer_config": None,
                        "attribute": "url",
                        "connector_config": None,
                        "description": "API endpoint",
                        "exist": True,
                        "for_organization": False,
                        "id": 353,
                        "ingestor_config": "GreedyBear",
                        "is_secret": False,
                        "organization": None,
                        "owner": None,
                        "parameter": 538,
                        "pivot_config": None,
                        "required": False,
                        "type": "str",
                        "value": "https://greedybear.honeynet.org",
                        "visualizer_config": None,
                    },
                    {
                        "analyzer_config": None,
                        "attribute": "limit",
                        "connector_config": None,
                        "description": "Max number of results.",
                        "exist": True,
                        "for_organization": False,
                        "id": 354,
                        "ingestor_config": "GreedyBear",
                        "is_secret": False,
                        "organization": None,
                        "owner": None,
                        "parameter": 539,
                        "pivot_config": None,
                        "required": False,
                        "type": "int",
                        "value": 50,
                        "visualizer_config": None,
                    },
                    {
                        "analyzer_config": None,
                        "attribute": "feed_type",
                        "connector_config": None,
                        "description": "The available feed types are log4j, cowrie, "
                        "and all.",
                        "exist": True,
                        "for_organization": False,
                        "id": 355,
                        "ingestor_config": "GreedyBear",
                        "is_secret": False,
                        "organization": None,
                        "owner": None,
                        "parameter": 540,
                        "pivot_config": None,
                        "required": False,
                        "type": "str",
                        "value": "all",
                        "visualizer_config": None,
                    },
                    {
                        "analyzer_config": None,
                        "attribute": "attack_type",
                        "connector_config": None,
                        "description": "The available attack_type are scanner, "
                        "payload_request, and all.",
                        "exist": True,
                        "for_organization": False,
                        "id": 356,
                        "ingestor_config": "GreedyBear",
                        "is_secret": False,
                        "organization": None,
                        "owner": None,
                        "parameter": 541,
                        "pivot_config": None,
                        "required": False,
                        "type": "str",
                        "value": "all",
                        "visualizer_config": None,
                    },
                    {
                        "analyzer_config": None,
                        "attribute": "age",
                        "connector_config": None,
                        "description": "The available age are recent and persistent.",
                        "exist": True,
                        "for_organization": False,
                        "id": 357,
                        "ingestor_config": "GreedyBear",
                        "is_secret": False,
                        "organization": None,
                        "owner": None,
                        "parameter": 542,
                        "pivot_config": None,
                        "required": False,
                        "type": "str",
                        "value": "recent",
                        "visualizer_config": None,
                    },
                ],
            },
        )
        # 2 - missing ingestor
        response = self.client.get(f"{self.URL}/missing_ingestor/plugin_config")
        self.assertEqual(response.status_code, 404, response.content)
        self.assertEqual(
            response.json(),
            {"errors": {"ingestor config": "Requested plugin does not exist."}},
        )
