{{- if .Values.integrations.pcapAnalyzers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intelowl.fullname" . }}-pcap-analyzers
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
    app.kubernetes.io/component: pcap-analyzers
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "intelowl.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pcap-analyzers
  template:
    metadata:
      labels:
        {{- include "intelowl.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pcap-analyzers
    spec:
      {{- include "intelowl.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "intelowl.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: pcap-analyzers
          image: "{{ .Values.integrations.pcapAnalyzers.image.repository }}:{{ .Values.integrations.pcapAnalyzers.image.tag | default .Values.app.version }}"
          imagePullPolicy: {{ .Values.integrations.pcapAnalyzers.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.integrations.pcapAnalyzers.service.port }}
              protocol: TCP
          env:
            {{- include "intelowl.commonEnvVars" . | nindent 12 }}
          volumeMounts:
            {{- include "intelowl.commonVolumeMounts" . | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.integrations.pcapAnalyzers.resources | nindent 12 }}
      volumes:
        {{- include "intelowl.commonVolumes" . | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "intelowl.fullname" . }}-pcap-analyzers
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
    app.kubernetes.io/component: pcap-analyzers
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.integrations.pcapAnalyzers.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "intelowl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pcap-analyzers
{{- end }}
