# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build all formats
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements/docs-requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py