# All additional integrations should be added following this format only.

services:
  bbot_analyzer:
    build:
      context: ../integrations/bbot
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_bbot_analyzer:${REACT_APP_INTELOWL_VERSION}
