# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '3.8'

# All additional integrations should be added following this format only.

services:
  malware_tools_analyzers:
    build:
      context: ../integrations/malware_tools_analyzers
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_malware_tools_analyzers:test
