# IMPORTANT: The version must match the version of docker-compose.yml
---
version: "3.8"

# All additional integrations should be added following this format only.

services:
  malware_tools_analyzers:
    image: intelowlproject/intelowl_malware_tools_analyzers:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_malware_tools_analyzers
    restart: unless-stopped
    expose:
      - "4002"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intel_owl
      - clam:/var/lib/clamav
      - ../integrations/malware_tools_analyzers/clamav:/etc/clamav
      - ../integrations/malware_tools_analyzers/qiling/rootfs:/opt/deploy/rootfs
      - ../integrations/malware_tools_analyzers/qiling/profiles:/opt/deploy/profiles
    depends_on:
      - uwsgi

volumes:
  clam:
