# Generated by Django 4.1.1 on 2023-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_factor_webauthn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webauthndevice",
            name="public_key",
            field=models.TextField(),
        ),
    ]

    def unapply(self, project_state, schema_editor, collect_sql=False):
        if schema_editor.connection.vendor == "mysql":
            # we avoided creating a unique index on long text.
            # fix the model so it reflects this.
            app_config = project_state.apps.get_app_config("two_factor_webauthn")
            model = app_config.get_model("webauthndevice")
            field = model._meta.get_field("public_key")
            field._unique = False

        return super().unapply(project_state, schema_editor, collect_sql)
