{{- if not .Values.externalSecrets.enabled }}
{{- if not .Values.app.django.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intelowl.fullname" . }}-app-secrets
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
  {{- if .Values.migration.enabled }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-12"
  {{- end }}
type: Opaque
data:
  {{- if .Values.app.django.secretKey }}
  django-secret: {{ .Values.app.django.secretKey | b64enc | quote }}
  {{- else }}
  django-secret: {{ randAlphaNum 50 | b64enc | quote }}
  {{- end }}

  {{- if not .Values.database.internal }}
  {{- if .Values.database.external.password }}
  db-password: {{ .Values.database.external.password | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if not .Values.broker.redis.internal }}
  {{- if .Values.broker.redis.external.password }}
  redis-password: {{ .Values.broker.redis.external.password | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if eq .Values.broker.type "rabbitmq" }}
  {{- if .Values.broker.rabbitmq.password }}
  rabbitmq-password: {{ .Values.broker.rabbitmq.password | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if eq .Values.broker.type "sqs" }}
  {{- if .Values.broker.sqs.accessKeyId }}
  aws-access-key-id: {{ .Values.broker.sqs.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.broker.sqs.secretAccessKey }}
  aws-secret-access-key: {{ .Values.broker.sqs.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if .Values.storage.s3.enabled }}
  {{- if not .Values.storage.s3.existingSecret }}
  {{- if .Values.storage.s3.accessKeyId }}
  aws-access-key-id: {{ .Values.storage.s3.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.s3.secretAccessKey }}
  aws-secret-access-key: {{ .Values.storage.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.flower.enabled }}
  {{- if .Values.flower.auth.enabled }}
  {{- if not .Values.flower.auth.existingSecret }}
  {{- if .Values.flower.auth.password }}
  flower-password: {{ .Values.flower.auth.password | b64enc | quote }}
  {{- else }}
  flower-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.app.slack.enabled }}
  {{- if not .Values.app.slack.existingSecret }}
  {{- if .Values.app.slack.token }}
  slack-token: {{ .Values.app.slack.token | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.app.email.enabled }}
  {{- if not .Values.app.email.existingSecret }}
  {{- if .Values.app.email.hostPassword }}
  email-password: {{ .Values.app.email.hostPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.superuser.enabled }}
  {{- if not .Values.superuser.existingSecret }}
  {{- if .Values.superuser.password }}
  superuser-password: {{ .Values.superuser.password | b64enc | quote }}
  {{- else }}
  superuser-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
