{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "intelowl.fullname" . }}-external-secrets
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "intelowl.fullname" . }}-app-secrets
    creationPolicy: Owner
  data:
    # Django secret key
    - secretKey: django-secret
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.djangoSecret.key | quote }}
        property: {{ .Values.externalSecrets.remoteRefs.djangoSecret.property | quote }}

    {{- if not .Values.database.internal }}
    # Database password
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.dbPassword.key | quote }}
        property: {{ .Values.externalSecrets.remoteRefs.dbPassword.property | quote }}
    {{- end }}

    {{- if not .Values.broker.redis.internal }}
    # Redis password
    - secretKey: redis-password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.redisPassword.key | quote }}
        property: {{ .Values.externalSecrets.remoteRefs.redisPassword.property | quote }}
    {{- end }}
{{- end }}
