services:
  uwsgi:
    depends_on:
      - postgres
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  daphne:
    depends_on:
      - redis
    command: daphne -b 0.0.0.0 -p 8001 intelowl.asgi:application

  celery_beat:
    depends_on:
      - postgres
      - redis
    command: celery -A intelowl beat -l info

  celery_worker_default:
    depends_on:
      - postgres
      - redis
    command: celery -A intelowl worker -l info -Q default