version: '3.8'

services:
  postgres:
    env_file:
      - env_file_postgres_template

  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_DOWNLOADER_ENABLED: ${REPO_DOWNLOADER_ENABLED}
    image: intelowlproject/intelowl:ci
    env_file:
      - env_file_app_ci
  
  daphne:
    image: intelowlproject/intelowl:ci
    env_file:
      - env_file_app_ci

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile_nginx
    image: intelowlproject/intelowl_nginx:ci
    volumes:
      - ../configuration/nginx/http.conf:/etc/nginx/conf.d/default.conf

  celery_beat:
    image: intelowlproject/intelowl:ci
    env_file:
      - env_file_app_ci

  celery_worker_default:
    image: intelowlproject/intelowl:ci
    env_file:
      - env_file_app_ci


