version: '3'

services:
  postgres:
    env_file:
      - env_file_postgres_template

  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - env_file_app_ci
    volumes:
      - ../coverage_reports:/opt/deploy/intel_owl/coverage_reports

  nginx:
    image: library/nginx:1.19-alpine
    volumes:
      - ../configuration/nginx_http.conf:/etc/nginx/conf.d/default.conf

  celery_beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - env_file_app_ci

  celery_worker_default:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - env_file_app_ci

volumes:
  postgres_data:
  nginx_logs:
  generic_logs:
  shared_files:

