version: '3'

services:
  postgres:
    env_file:
      - env_file_postgres_template

  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - env_file_app_ci

  celery_beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - env_file_app_ci

  celery_worker_default:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - env_file_app_ci

