FROM library/nginx:1.29.2-alpine

RUN apk add --no-cache bash curl

ENV NGINX_LOG_DIR=/var/log/nginx

# this is to avoid having logs redirected to stdout/stderr
RUN rm $NGINX_LOG_DIR/access.log $NGINX_LOG_DIR/error.log \
    && touch $NGINX_LOG_DIR/access.log $NGINX_LOG_DIR/error.log

VOLUME /var/log/nginx
