services:
  uwsgi:
    depends_on:
      - elasticsearch
    volumes:
      - ../certs:/opt/deploy/intel_owl/certs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: intelowl_elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9200 || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 2s
      retries: 6
    env_file:
      - env_file_app
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ../certs:/usr/share/elasticsearch/config/certificates
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false

volumes:
  elastic_data: