services:
  traefik:
    image: "traefik:3.0"
    container_name: "traefik"
    command:
      # Pleases refer to the official documentation: https://doc.traefik.io/traefik/
      # DASHBOARD
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # LOGS
      - "--log.level=DEBUG"
      # PROVIDERS
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      # ENTRYPOINTS
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
      depends_on:
        - traefik
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`localhost`)"
        - "traefik.http.routers.nginx.entrypoints=web"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
      expose: 
        - "80"

