{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "intelowl.fullname" . }}-celery
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "intelowl.selectorLabels" . | nindent 6 }}
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - celery-worker-default
          - celery-worker-local
          - celery-worker-long
          - celery-worker-ingestor
          - celery-beat
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.podMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout }}
{{- end }}
