#!/bin/bash

if [[ "$SOURCE_BRANCH" == "test_arm" ]]; then
  curl -d "text=A new production image has been pushed to Docker Hub" -d "channel=$SLACK_CHANNEL" -H "Authorization: Bearer $SLACK_TOKEN" -X POST https://slack.com/api/chat.postMessage
fi