openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/ask_analysis_availability:
    get:
      operationId: api_ask_analysis_availability_retrieve
      description: |-
        This is useful to avoid repeating the same analysis multiple times.
        By default this API checks if there are existing analysis related to the md5 in
        status "running" or "reported_without_fails"
        Also, you need to specify the analyzers needed because, otherwise, it is
        highly probable that you won't get all the results that you expect

        :param str md5: md5 of the sample or observable to look for
        :param list analyzers_needed: specify analyzers needed. It requires either this
            or run_all_available_analyzers
        :param bool run_all_available_analyzers:
            if we are looking for an analysis executed with this flag set
        :param bool running_only: check only for running analysis,
            default False, any value is True
        :returns:
            - 200 - if ok with list of all analysis related to that md5
            - 500 - if failed
      tags:
      - api
      responses:
        '200':
          description: No response body
  /api/auth/login:
    post:
      operationId: api_auth_login_create
      description: |-
        Durin's Login View.

        This view will return a JSON response when valid ``username``, ``password`` and
        if not overwritten ``client`` fields are POSTed to the view using
        form data or JSON.

        It uses the default serializer provided by
        Django-Rest-Framework (``rest_framework.authtoken.serializers.AuthTokenSerializer``)
        to validate the user credentials.

        It is possible to customize LoginView behaviour by overriding the following
        helper methods:
      tags:
      - api
      responses:
        '200':
          description: No response body
  /api/auth/logout:
    post:
      operationId: api_auth_logout_create
      description: |-
        Durin's Logout View.

        This view accepts only a post request with an empty body.
        It responds to Durin Token Authentication. On a successful request,

        1. The token used to authenticate is deleted from
           the database and can no longer be used to authenticate.

        2. :meth:`django.contrib.auth.signals.user_logged_out` is called.

        :returns: 204 (No content)
      tags:
      - api
      responses:
        '200':
          description: No response body
  /api/download_sample:
    get:
      operationId: api_download_sample_retrieve
      description: |-
        This method is used to download a sample from a Job ID

        :param request: job_id
        :returns:
            - 200 - if found
            - 404 - not found
            - 403 - forbidden
      tags:
      - api
      responses:
        '200':
          description: No response body
  /api/get_analyzer_configs:
    get:
      operationId: api_get_analyzer_configs_retrieve
      description: |-
        Get the uploaded analyzer configuration,
        can be useful if you want to choose the analyzers programmatically

        :returns:
            - 200 - if ok
            - 500 - if failed
      tags:
      - api
      responses:
        '200':
          description: No response body
  /api/jobs:
    get:
      operationId: api_jobs_list
      description: |-
        REST endpoint to fetch list of jobs or retrieve a job with job ID.
        Requires authentication.

        :methods_allowed:
            GET, OPTIONS, DELETE

        :returns:
            - 200 - if GET ok
            - 204 - if DELETE ok
            - 404 if not found
            - 405 if wrong HTTP method
      tags:
      - api
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobList'
          description: ''
  /api/jobs/{id}:
    get:
      operationId: api_jobs_retrieve
      description: |-
        REST endpoint to fetch list of jobs or retrieve a job with job ID.
        Requires authentication.

        :methods_allowed:
            GET, OPTIONS, DELETE

        :returns:
            - 200 - if GET ok
            - 204 - if DELETE ok
            - 404 if not found
            - 405 if wrong HTTP method
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this job.
        required: true
      tags:
      - api
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
    delete:
      operationId: api_jobs_destroy
      description: |-
        REST endpoint to fetch list of jobs or retrieve a job with job ID.
        Requires authentication.

        :methods_allowed:
            GET, OPTIONS, DELETE

        :returns:
            - 200 - if GET ok
            - 204 - if DELETE ok
            - 404 if not found
            - 405 if wrong HTTP method
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this job.
        required: true
      tags:
      - api
      responses:
        '204':
          description: No response body
  /api/jobs/{id}/kill:
    patch:
      operationId: api_jobs_kill_partial_update
      description: |-
        Kill running job by closing celery tasks and marking as killed

        :param url: pk (job_id)
        :returns:
         - 200 - if killed
         - 404 - not found
         - 403 - forbidden, 400 bad request
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this job.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedJob'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedJob'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedJob'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
  /api/send_analysis_request:
    post:
      operationId: api_send_analysis_request_create
      description: |-
        This endpoint allows to start a Job related to a file or an observable

        :param bool is_sample: is a sample (file) or an observable (domain, ip, ...)
        :param str md5:  md5 of the item to analyze
        :param binary file: required if is_sample=True, the binary
        :param str file_mimetype:  optional, the binary mimetype, calculated by default
        :param str file_name: optional if is_sample=True, the binary name
        :param str observable_name:  required if is_sample=False, the observable value
        :param str observable_classification: required if is_sample=False, (domain, ip, ...)
        :param list analyzers_requested: list of requested analyzer to run, before filters
        :param list<int> tags_id: list of id's of tags to apply to job
        :param bool run_all_available_analyzers: default False
        :param bool private: default False,
            enable it to allow view permissions to only requesting user's groups.
        :param bool force_privacy: default False,
            enable it if you want to avoid to run analyzers with privacy issues
        :param bool disable_external_analyzers: default False,
            enable it if you want to exclude external analyzers
        :param dict runtime_configuration: default {},
            contains additional parameters for particular analyzers
        :param bool test: disable analysis for API testing

        :returns:
            - 202 - if accepted
            - 500 - if failed
      tags:
      - api
      responses:
        '200':
          description: No response body
  /api/tags:
    get:
      operationId: api_tags_list
      description: |-
        REST endpoint to pefrom CRUD operations on Job tags.
        Requires authentication.
        POST/PUT/DELETE requires model/object level permission.

        :methods_allowed:
            GET, POST, PUT, DELETE, OPTIONS

        :returns:
            - 200 - if ok
            - 404 - if not found
            - 405 - if wrong HTTP method
      tags:
      - api
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
          description: ''
    post:
      operationId: api_tags_create
      description: |-
        REST endpoint to pefrom CRUD operations on Job tags.
        Requires authentication.
        POST/PUT/DELETE requires model/object level permission.

        :methods_allowed:
            GET, POST, PUT, DELETE, OPTIONS

        :returns:
            - 200 - if ok
            - 404 - if not found
            - 405 - if wrong HTTP method
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
  /api/tags/{id}:
    get:
      operationId: api_tags_retrieve
      description: |-
        REST endpoint to pefrom CRUD operations on Job tags.
        Requires authentication.
        POST/PUT/DELETE requires model/object level permission.

        :methods_allowed:
            GET, POST, PUT, DELETE, OPTIONS

        :returns:
            - 200 - if ok
            - 404 - if not found
            - 405 - if wrong HTTP method
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - api
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
    put:
      operationId: api_tags_update
      description: |-
        REST endpoint to pefrom CRUD operations on Job tags.
        Requires authentication.
        POST/PUT/DELETE requires model/object level permission.

        :methods_allowed:
            GET, POST, PUT, DELETE, OPTIONS

        :returns:
            - 200 - if ok
            - 404 - if not found
            - 405 - if wrong HTTP method
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
    patch:
      operationId: api_tags_partial_update
      description: |-
        REST endpoint to pefrom CRUD operations on Job tags.
        Requires authentication.
        POST/PUT/DELETE requires model/object level permission.

        :methods_allowed:
            GET, POST, PUT, DELETE, OPTIONS

        :returns:
            - 200 - if ok
            - 404 - if not found
            - 405 - if wrong HTTP method
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTag'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
    delete:
      operationId: api_tags_destroy
      description: |-
        REST endpoint to pefrom CRUD operations on Job tags.
        Requires authentication.
        POST/PUT/DELETE requires model/object level permission.

        :methods_allowed:
            GET, POST, PUT, DELETE, OPTIONS

        :returns:
            - 200 - if ok
            - 404 - if not found
            - 405 - if wrong HTTP method
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tag.
        required: true
      tags:
      - api
      responses:
        '204':
          description: No response body
components:
  schemas:
    Job:
      type: object
      description: |-
        Job model's serializer.
        Used for create(), retrieve()
      properties:
        id:
          type: integer
          readOnly: true
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          readOnly: true
        tags_id:
          type: array
          items:
            type: integer
            writeOnly: true
          writeOnly: true
        source:
          type: string
          maxLength: 50
        is_sample:
          type: boolean
        md5:
          type: string
          maxLength: 32
        observable_name:
          type: string
          maxLength: 512
        observable_classification:
          type: string
          maxLength: 12
        file_name:
          type: string
          maxLength: 512
        file_mimetype:
          type: string
          maxLength: 80
        status:
          $ref: '#/components/schemas/StatusEnum'
        analyzers_requested:
          type: array
          items:
            type: string
        run_all_available_analyzers:
          type: boolean
        analyzers_to_execute:
          type: array
          items:
            type: string
        analysis_reports:
          type: object
          additionalProperties: {}
          nullable: true
        received_request_time:
          type: string
          format: date-time
          readOnly: true
        finished_analysis_time:
          type: string
          format: date-time
          nullable: true
        force_privacy:
          type: boolean
        disable_external_analyzers:
          type: boolean
        errors:
          type: array
          items:
            type: string
          nullable: true
        file:
          type: string
          format: uri
          writeOnly: true
        runtime_configuration:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - id
      - md5
      - received_request_time
      - tags
      - tags_id
    JobList:
      type: object
      description: |-
        Job model's list serializer.
        Used for list()
      properties:
        id:
          type: integer
          readOnly: true
        is_sample:
          type: boolean
        observable_name:
          type: string
          maxLength: 512
        observable_classification:
          type: string
          maxLength: 12
        file_name:
          type: string
          maxLength: 512
        file_mimetype:
          type: string
          maxLength: 80
        status:
          $ref: '#/components/schemas/StatusEnum'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          readOnly: true
        process_time:
          type: string
          readOnly: true
        no_of_analyzers_executed:
          type: string
          readOnly: true
      required:
      - id
      - no_of_analyzers_executed
      - process_time
      - tags
    PatchedJob:
      type: object
      description: |-
        Job model's serializer.
        Used for create(), retrieve()
      properties:
        id:
          type: integer
          readOnly: true
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          readOnly: true
        tags_id:
          type: array
          items:
            type: integer
            writeOnly: true
          writeOnly: true
        source:
          type: string
          maxLength: 50
        is_sample:
          type: boolean
        md5:
          type: string
          maxLength: 32
        observable_name:
          type: string
          maxLength: 512
        observable_classification:
          type: string
          maxLength: 12
        file_name:
          type: string
          maxLength: 512
        file_mimetype:
          type: string
          maxLength: 80
        status:
          $ref: '#/components/schemas/StatusEnum'
        analyzers_requested:
          type: array
          items:
            type: string
        run_all_available_analyzers:
          type: boolean
        analyzers_to_execute:
          type: array
          items:
            type: string
        analysis_reports:
          type: object
          additionalProperties: {}
          nullable: true
        received_request_time:
          type: string
          format: date-time
          readOnly: true
        finished_analysis_time:
          type: string
          format: date-time
          nullable: true
        force_privacy:
          type: boolean
        disable_external_analyzers:
          type: boolean
        errors:
          type: array
          items:
            type: string
          nullable: true
        file:
          type: string
          format: uri
          writeOnly: true
        runtime_configuration:
          type: object
          additionalProperties: {}
          nullable: true
    PatchedTag:
      type: object
      description: |-
        A serializer mixin that provides an easy way to assign permissions
        to given users and/or group when an object is created or updated.
      properties:
        id:
          type: integer
          readOnly: true
        label:
          type: string
          maxLength: 50
        color:
          type: string
          maxLength: 7
    StatusEnum:
      enum:
      - pending
      - running
      - reported_without_fails
      - reported_with_fails
      - failed
      - killed
      type: string
    Tag:
      type: object
      description: |-
        A serializer mixin that provides an easy way to assign permissions
        to given users and/or group when an object is created or updated.
      properties:
        id:
          type: integer
          readOnly: true
        label:
          type: string
          maxLength: 50
        color:
          type: string
          maxLength: 7
      required:
      - color
      - id
      - label
