# Generated by Django 4.2.8 on 2024-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={"verbose_name_plural": "analyses"},
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["start_time"], name="analyses_ma_start_t_6a1f30_idx"
            ),
        ),
    ]
