# Generated by Django 4.1.9 on 2023-06-09 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_app', '0030_pluginconfig_repositories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzers_manager', '0031_alter_analyzerconfig_name'),
        ('playbooks_manager', '0014_playbookconfig_disabled_in_organizations'),
        ('visualizers_manager', '0022_alter_visualizerconfig_name'),
        ('certego_saas_organization', '0001_initial'),
        ('connectors_manager', '0018_alter_connectorconfig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotConfig',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$', 'Your name should match the [A-Za-z0-9_] characters')])),
                ('description', models.TextField()),
                ('disabled', models.BooleanField(default=False)),
                ('field', models.CharField(help_text='Dotted path to the field', max_length=256)),
                ('analyzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pivots', to='analyzers_manager.analyzerconfig')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pivots', to='connectors_manager.connectorconfig')),
                ('disabled_in_organizations', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_disabled', to='certego_saas_organization.organization')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pivots', to='playbooks_manager.playbookconfig')),
                ('visualizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pivots', to='visualizers_manager.visualizerconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pivot_manager.pivotconfig')),
                ('ending_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_parents', to='api_app.job')),
                ('starting_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_children', to='api_app.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='pivotconfig',
            index=models.Index(fields=['analyzer', 'field', 'playbook'], name='pivot_manag_analyze_bd2caf_idx'),
        ),
        migrations.AddIndex(
            model_name='pivotconfig',
            index=models.Index(fields=['connector', 'field', 'playbook'], name='pivot_manag_connect_6b9bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='pivotconfig',
            index=models.Index(fields=['visualizer', 'field', 'playbook'], name='pivot_manag_visuali_923691_idx'),
        ),
        migrations.AddIndex(
            model_name='pivotconfig',
            index=models.Index(fields=['analyzer'], name='pivot_manag_analyze_af25ec_idx'),
        ),
        migrations.AddIndex(
            model_name='pivotconfig',
            index=models.Index(fields=['connector'], name='pivot_manag_connect_493541_idx'),
        ),
        migrations.AddIndex(
            model_name='pivotconfig',
            index=models.Index(fields=['visualizer'], name='pivot_manag_visuali_4eba9d_idx'),
        ),
        migrations.AddIndex(
            model_name='pivotconfig',
            index=models.Index(fields=['playbook'], name='pivot_manag_playboo_97689c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pivotconfig',
            unique_together={('analyzer', 'connector', 'visualizer', 'field', 'playbook')},
        ),
        migrations.AddIndex(
            model_name='pivot',
            index=models.Index(fields=['starting_job'], name='pivot_manag_startin_21e74a_idx'),
        ),
        migrations.AddIndex(
            model_name='pivot',
            index=models.Index(fields=['ending_job'], name='pivot_manag_ending__6d1c06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pivot',
            unique_together={('starting_job', 'config', 'ending_job')},
        ),
    ]
