{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "intelowl.fullname" . }}-flower
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: flower
      protocol: TCP
      name: flower
  selector:
    {{- include "intelowl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flower
{{- end }}
