# Generated by Django 4.2.25 on 2025-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_events_manager", "0002_alter_userdomainwildcardevent_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranalyzableevent",
            name="data_model_object_id",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
