# Generated by Django 4.2.25 on 2025-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_events_manager", "0002_alter_userdomainwildcardevent_query"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useranalyzableevent",
            index=models.Index(
                fields=["data_model_content_type", "data_model_object_id"],
                name="user_events_data_mo_ed1d0e_idx",
            ),
        ),
    ]
