# Generated by Django 4.2.25 on 2025-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_events_manager", "0003_user_analyzer_event_data_model_id_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranalyzableevent",
            name="reason",
            field=models.CharField(default="", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userdomainwildcardevent",
            name="reason",
            field=models.CharField(default="", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="useripwildcardevent",
            name="reason",
            field=models.CharField(default="", max_length=256, null=True),
        ),
    ]
