# Generated by Django 3.2.15 on 2022-11-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_app', '0011_alter_organizationpluginstate_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPlaybook',
            fields=[
                ('name', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=225)),
                ('analyzers', models.JSONField(default=dict)),
                ('connectors', models.JSONField(default=dict)),
                ('supports', models.JSONField(default=list)),
                ('default', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.job')),
            ],
        ),
    ]
