# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.15 on 2022-11-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_app", "0011_alter_organizationpluginstate_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedPlaybook",
            fields=[
                (
                    "name",
                    models.CharField(max_length=225, primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                ("analyzers", models.JSONField(default=dict)),
                ("connectors", models.JSONField(default=dict)),
                ("supports", models.JSONField(default=list)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True,
                        to="api_app.job",
                        related_name="job",
                    ),
                ),
            ],
        ),
    ]
