# Generated by Django 3.2.15 on 2023-01-05 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certego_saas_organization', '0001_initial'),
        ('playbooks_manager', '0002_auto_20221120_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedplaybook',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cachedplaybook_organization', to='certego_saas_organization.organization'),
        ),
        migrations.AlterField(
            model_name='cachedplaybook',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cachedplaybook_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
