# Generated by Django 3.2.18 on 2023-02-22 13:53

from django.db import migrations, models

import api_app.fields
import api_app.playbooks_manager.models
import api_app.playbooks_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0003_analyzerconfig'),
        ('connectors_manager', '0003_connectorconfig'),
        ('playbooks_manager', '0002_alter_cachedplaybook_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookConfig',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('type', api_app.fields.ChoiceArrayField(
                    base_field=models.CharField(
                        choices=[('ip', 'Ip'), ('url', 'Url'), ('domain', 'Domain'), ('hash', 'Hash'), ('generic', 'Generic'), ('file', 'File')],
                        max_length=50), size=None),
                 ),
                ('description', models.TextField()),
                ('disabled', models.BooleanField(default=False)),
                ('runtime_configuration', models.JSONField(blank=True, default=api_app.playbooks_manager.models.default_runtime, validators=[api_app.playbooks_manager.validators.validate_runtime_configuration_playbook])),
                ('analyzers', models.ManyToManyField(related_name='playbooks', to='analyzers_manager.AnalyzerConfig', blank=True)),
                ('connectors', models.ManyToManyField(related_name='playbooks', to='connectors_manager.ConnectorConfig', blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CachedPlaybook',
        ),
    ]
