# Generated by Django 4.1.9 on 2023-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playbooks_manager", "0008_fix_free_to_use_playbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbookconfig",
            name="name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
