# Generated by Django 4.1.9 on 2023-06-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_manager', '0014_dns_playbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbookconfig',
            options={'ordering': ['name', 'disabled']},
        ),
    ]
