# Generated by Django 4.1.10 on 2023-10-03 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playbooks_manager", "0019_update_static_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbookconfig",
            name="for_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="playbookconfig",
            index=models.Index(
                fields=["owner", "for_organization"],
                name="playbooks_m_owner_i_88fb49_idx",
            ),
        ),
    ]
