# Generated by Django 4.1.10 on 2023-10-04 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0019_update_static_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playbookconfig",
            name="pivots",
        ),
    ]
