# Generated by Django 4.1.10 on 2023-10-03 08:26

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "playbooks_manager",
            "0020_playbookconfig_for_organization_playbookconfig_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbookconfig",
            name="name",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$", "Your name should match the [A-Za-z0-9_] characters"
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playbookconfig",
            unique_together={("name", "owner")},
        ),
    ]
