# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.contrib.postgres.fields
from django.contrib.postgres.expressions import ArraySubquery
from django.db import migrations, models


def migrate(apps, schema_editor):
    Playbook = apps.get_model("playbooks_manager", "PlaybookConfig")
    Playbook.objects.update(
        analyzers2=ArraySubquery(
            Playbook.objects.filter(pk=models.OuterRef("pk")).values("analyzers__name")
        ),
        connectors2=ArraySubquery(
            Playbook.objects.filter(pk=models.OuterRef("pk")).values("connectors__name")
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0058_1_change_primary_key"),
        ("connectors_manager", "0029_1_change_primary_key"),
        ("playbooks_manager", "0002_0004_playbook_config_sample_static_analysis"),
        ("visualizers_manager", "0001_initial_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbookconfig",
            name="analyzers2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="connectors2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(
            model_name="playbookconfig",
            name="analyzers",
        ),
        migrations.RemoveField(
            model_name="playbookconfig",
            name="connectors",
        ),
    ]
