# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations, models


def migrate(apps, schema_editor):
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    id = 1
    for config in PlaybookConfig.objects.all():
        config.id = id
        config.save()
        id += 1


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0023_4_change_primary_key"),
        ("api_app", "0057_4_change_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbookconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.AlterField(
            model_name="playbookconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
            ),
        ),
    ]
