# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.contrib.postgres.fields
from django.contrib.postgres.expressions import ArraySubquery
from django.db import migrations, models


def migrate(apps, schema_editor):
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    PlaybookConfig.objects.update(
        pivots2=ArraySubquery(
            PlaybookConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "pivots__name"
            )
        ),
        analyzers2=ArraySubquery(
            PlaybookConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "analyzers__name"
            )
        ),
        connectors2=ArraySubquery(
            PlaybookConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "connectors__name"
            )
        ),
        tags2=ArraySubquery(
            PlaybookConfig.objects.filter(pk=models.OuterRef("pk")).values("tags__pk")
        ),
        disabled2=ArraySubquery(
            PlaybookConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "disabled_in_organizations__pk"
            )
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0023_4_change_primary_key"),
        ("pivots_manager", "0001_2_initial_squashed"),
        ("api_app", "0057_4_change_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbookconfig",
            name="disabled2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="pivots2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="connectors2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="analyzers2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="tags2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(model_name="playbookconfig", name="pivots"),
        migrations.RemoveField(
            model_name="playbookconfig",
            name="analyzers",
        ),
        migrations.RemoveField(
            model_name="playbookconfig",
            name="connectors",
        ),
        migrations.RemoveField(
            model_name="playbookconfig",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="playbookconfig", name="disabled_in_organizations"
        ),
    ]
