# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations, models


def migrate(apps, schema_editor):
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    PivotConfig = apps.get_model("pivots_manager", "PivotConfig")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    Organization = apps.get_model("certego_saas_organization", "Organization")
    Tag = apps.get_model("api_app", "Tag")
    for playbook in PlaybookConfig.objects.all():
        pivots = PivotConfig.objects.filter(name__in=playbook.pivots2).values_list(
            "pk", flat=True
        )
        acs = AnalyzerConfig.objects.filter(name__in=playbook.analyzers2).values_list(
            "pk", flat=True
        )
        ccs = ConnectorConfig.objects.filter(name__in=playbook.connectors2).values_list(
            "pk", flat=True
        )
        tags = Tag.objects.filter(pk__in=playbook.tags2).values_list("pk", flat=True)
        playbook.pivots.set(pivots)
        playbook.analyzers.set(acs)
        playbook.connectors.set(ccs)
        playbook.tags.set(tags)
        if playbook.disabled2:
            OrganizationPluginConfiguration = apps.get_model(
                "api_app", "OrganizationPluginConfiguration"
            )
            ContentType = apps.get_model("contenttypes", "ContentType")
            ct = ContentType.objects.get_for_model(playbook)
            for org in playbook.disabled2:
                if org:
                    OrganizationPluginConfiguration.objects.create(
                        organization=Organization.objects.get(pk=org),
                        object_id=playbook.pk,
                        content_type=ct,
                        disabled=True,
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0001_2_initial_squashed"),
        ("playbooks_manager", "0024_3_change_primary_key"),
        ("pivots_manager", "0001_2_initial_squashed"),
        ("analyzers_manager", "0058_3_change_primary_key"),
        ("connectors_manager", "0029_3_change_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbookconfig",
            name="pivots",
            field=models.ManyToManyField(
                blank=True,
                related_name="used_by_playbooks",
                to="pivots_manager.PivotConfig",
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="analyzers",
            field=models.ManyToManyField(
                blank=True,
                related_name="playbooks",
                to="analyzers_manager.AnalyzerConfig",
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="connectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="playbooks",
                to="connectors_manager.ConnectorConfig",
            ),
        ),
        migrations.AddField(
            model_name="playbookconfig",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="playbooks",
                to="api_app.Tag",
            ),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(model_name="playbookconfig", name="pivots2"),
        migrations.RemoveField(model_name="playbookconfig", name="analyzers2"),
        migrations.RemoveField(model_name="playbookconfig", name="connectors2"),
        migrations.RemoveField(model_name="playbookconfig", name="tags2"),
        migrations.RemoveField(model_name="playbookconfig", name="disabled2"),
    ]
