# Generated by Django 4.2.11 on 2024-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0036_static_analyzer_remove_visualizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbookconfig",
            name="starting",
            field=models.BooleanField(
                default=True,
                help_text="If False, the playbook can only be executed by pivots",
            ),
        ),
    ]
