# Generated by Django 4.2.11 on 2024-05-07 13:54

from django.db import migrations

playbooks_to_change = ["Abuse_IP"]


def migrate(apps, schema_editor):
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    for pc in PlaybookConfig.objects.filter(name__in=playbooks_to_change):
        pc.starting = False
        pc.save()


def reverse_migrate(apps, schema_editor):
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    for pc in PlaybookConfig.objects.filter(name__in=playbooks_to_change):
        pc.starting = True
        pc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0037_playbookconfig_starting"),
    ]

    operations = [
        migrations.RunPython(migrate, reverse_migrate),
    ]
