# Generated by Django 4.2.11 on 2024-05-09 12:55

import datetime

from django.db import migrations, models


def migrate(apps, schema_editor):
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    PlaybookConfig.objects.filter(starting=False).update(
        scan_mode=1, scan_check_time=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0038_playbooks_not_starting"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="playbookconfig",
            name="scan_check_time",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(days=1),
                help_text="Time range checked if the scan_mode is set to `check_previous_analysis`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playbookconfig",
            name="scan_mode",
            field=models.IntegerField(
                choices=[(1, "Force New Analysis"), (2, "Check Previous Analysis")],
                default=2,
                help_text="If it's not a starting playbook, this must be set to `check_previous_analysis`",
            ),
        ),
    ]
