# Generated by Django 4.2.17 on 2025-01-15 09:34

import django.contrib.postgres.fields
from django.db import migrations, models

import api_app.engines_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ("engines_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineconfig",
            name="modules",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=255,
                    validators=[
                        api_app.engines_manager.validators.validate_engine_module
                    ],
                ),
                blank=True,
                default=list,
                help_text="List of modules used by the engine. Each module has syntax `name_file.name_class`",
                size=None,
            ),
        ),
    ]
