# Generated by Django 4.2.17 on 2025-01-15 09:34

import api_app.engines_manager.validators
import django.contrib.postgres.fields
from django.db import migrations, models

def migrate(apps, schema_editor):
    EngineConfig = apps.get_model('engines_manager', 'EngineConfig')
    EngineConfig.objects.create(
        modules=[
            "evaluation.EvaluationEngineModule"
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('engines_manager', '0002_alter_engineconfig_modules'),
    ]

    operations = [
        migrations.RunPython(
            migrate, migrations.RunPython.noop
        ),
    ]
