# IMPORTANT: The version must match the version of docker-compose.yml
---
version: "3.8"

# All additional integrations should be added following this format only.

services:
  rendertron:
    image: intelowlproject/intelowl_rendertron:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_rendertron
    restart: unless-stopped
    expose:
      - "4003"
    security_opt:
      - seccomp:./integrations/rendertron/seccomp/chrome.json
