# Generated by Django 3.1.3 on 2020-11-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0003_auto_20201020_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="file_name",
            field=models.CharField(blank=True, max_length=512),
        )
    ]
