# Generated by Django 3.2.4 on 2021-06-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20201112_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='analysis_reports',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='runtime_configuration',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('reported_without_fails', 'reported_without_fails'), ('reported_with_fails', 'reported_with_fails'), ('failed', 'failed'), ('killed', 'killed')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
