# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.5 on 2021-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0006_v3_release"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=7),
        ),
    ]
