# Generated by Django 3.2.4 on 2021-07-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0006_job_connectors_to_execute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="analysis_reports",
        ),
    ]
