# Generated by Django 3.2.5 on 2021-08-26 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_app", "0006_v3_release")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="connectors_requested",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("running", "running"),
                    ("reported_without_fails", "reported_without_fails"),
                    ("reported_with_fails", "reported_with_fails"),
                    ("killed", "killed"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
