# Generated by Django 3.2.5 on 2021-08-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_app", "0006_v3_release")]

    operations = [
        migrations.RemoveField(model_name="job", name="disable_external_analyzers"),
        migrations.RemoveField(model_name="job", name="force_privacy"),
        migrations.AddField(
            model_name="job",
            name="tlp",
            field=models.CharField(
                choices=[
                    ("WHITE", "White"),
                    ("GREEN", "Green"),
                    ("AMBER", "Amber"),
                    ("RED", "Red"),
                ],
                default="WHITE",
                max_length=8,
            ),
        ),
    ]
