# Generated by Django 3.2.11 on 2022-01-18 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_app", "0007_alter_tag_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="source",
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
