# Generated by Django 3.2.4 on 2021-07-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0007_remove_job_analysis_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="runtime_configuration",
        ),
    ]
