# Generated by Django 3.2.14 on 2022-07-22 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certego_saas_organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_app", "0009_datamigration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Analyzer"), ("2", "Connector")], max_length=2
                    ),
                ),
                ("attribute", models.CharField(max_length=128)),
                ("value", models.JSONField()),
                ("plugin_name", models.CharField(max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_configs",
                        to="certego_saas_organization.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="customconfig",
            index=models.Index(
                fields=["owner", "type"], name="api_app_cus_owner_i_e8ba4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customconfig",
            index=models.Index(
                fields=["type", "organization"], name="api_app_cus_type_68283e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customconfig",
            constraint=models.UniqueConstraint(
                fields=("type", "attribute", "organization", "owner"),
                name="unique_custom_config_entry",
            ),
        ),
    ]
