# Generated by Django 3.2.14 on 2022-07-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0010_customconfig"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customconfig",
            old_name="name",
            new_name="plugin_name",
        ),
    ]
