# Generated by Django 3.2.14 on 2022-08-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0010_custom_config"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomConfig",
            new_name="PluginConfig",
        ),
    ]
