# Generated by Django 3.2.14 on 2022-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_customconfig_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pluginconfig',
            name='api_app_cus_owner_i_e8ba4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='pluginconfig',
            name='api_app_cus_type_68283e_idx',
        ),
        migrations.AddField(
            model_name='pluginconfig',
            name='config_type',
            field=models.CharField(choices=[('1', 'Parameter'), ('2', 'Secret')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pluginconfig',
            index=models.Index(fields=['owner', 'type'], name='api_app_plu_owner_i_ff141f_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginconfig',
            index=models.Index(fields=['type', 'organization'], name='api_app_plu_type_92301a_idx'),
        ),
    ]
