# Generated by Django 3.2.16 on 2022-12-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0011_alter_organizationpluginstate_organization"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pluginconfig",
            name="unique_custom_config_entry",
        ),
        migrations.AddConstraint(
            model_name="pluginconfig",
            constraint=models.UniqueConstraint(
                fields=("type", "attribute", "organization", "owner", "plugin_name"),
                name="unique_custom_config_entry",
            ),
        ),
    ]
