# Generated by Django 3.2.14 on 2022-07-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0011_rename_name_customconfig_plugin_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customconfig",
            index=models.Index(
                fields=["owner", "type"], name="api_app_cus_owner_i_e8ba4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customconfig",
            index=models.Index(
                fields=["type", "organization"], name="api_app_cus_type_68283e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customconfig",
            constraint=models.UniqueConstraint(
                fields=("type", "attribute", "organization", "owner"),
                name="unique_custom_config_entry",
            ),
        ),
    ]
