# Generated by Django 3.2.14 on 2022-10-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0011_playbooks"),
        ("api_app", "0013_auto_20220912_1151"),
    ]

    operations = []
