# Generated by Django 3.2.18 on 2023-02-17 17:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_add_job_process_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visualizers_to_execute',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='organizationpluginstate',
            name='type',
            field=models.CharField(choices=[('1', 'Analyzer'), ('2', 'Connector'), ('3', 'Visualizer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='type',
            field=models.CharField(choices=[('1', 'Analyzer'), ('2', 'Connector'), ('3', 'Visualizer')], max_length=2),
        ),
        migrations.CreateModel(
            name='VisualizerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('FAILED', 'Failed'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('KILLED', 'Killed')], max_length=50)),
                ('report', models.JSONField(default=dict)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, size=None)),
                ('runtime_configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_id', models.UUIDField()),
                ('parent_playbook', models.CharField(blank=True, default='', max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizer_reports', to='api_app.job')),
            ],
            options={
                'unique_together': {('name', 'job')},
            },
        ),
    ]
