# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-02-22 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_add_job_process_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visualizers_to_execute',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='organizationpluginstate',
            name='type',
            field=models.CharField(choices=[('1', 'Analyzer'), ('2', 'Connector'), ('3', 'Visualizer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='type',
            field=models.CharField(choices=[('1', 'Analyzer'), ('2', 'Connector'), ('3', 'Visualizer')], max_length=2),
        ),
    ]