# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-03-07 08:29
import django
from django.conf import settings
from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0024_tlp'),
        ('analyzers_manager', '0015_alter_analyzerconfig_disabled_in_organizations_and_more'),
        ('connectors_manager', '0014_alter_connectorconfig_disabled_in_organizations_and_more'),
        ('visualizers_manager', '0012_alter_visualizerconfig_disabled_in_organizations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name", models.CharField(null=False, blank=False, max_length=50)
                ),
                (
                    "type", models.CharField(choices=[('int', 'Int'), ('float', 'Float'), ('str', 'Str'), ('bool', 'Bool'), ('list', 'List'), ('dict', 'Dict')], max_length=10)
                ),
                (
                    "description", models.TextField(
                        default="", blank=True
                    )
                ),
                (
                    "is_secret", models.BooleanField(
                    )
                )
            ],
            options={"unique_together": {("name", "type", "is_secret")}},
        ),
        migrations.CreateModel(
            name="ParameterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                (
                    "parameter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api_app.parameter")
                ),
                (
                    "required", models.BooleanField(
                    )
                )
            ],
            options={"unique_together": {("parameter", "required")}},
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_configs",
                to=settings.AUTH_USER_MODEL,
                null=True,
                blank=True
            ),
        ),
    ]
