# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-03-07 08:29
import django
from django.db import migrations, models

def migrate_plugin_config(apps, schema_editor):
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")

    for plugin_config in PluginConfig.objects.all():
        plugin_config.for_organization = plugin_config.organization is not None
        if plugin_config.type == "1":
            class_ = AnalyzerConfig
        elif plugin_config.type == "2":
            class_ = ConnectorConfig
        elif plugin_config.type == "3":
            class_ = VisualizerConfig
        else:
            raise RuntimeError("Not configured")
        params = class_.objects.get(name=plugin_config.plugin_name).parameters
        plugin_config.parameter = params.get(parameter__name=plugin_config.attribute).parameter
        plugin_config.full_clean()
        plugin_config.save()

def reverse_migrate_plugin_config(apps, schema_editor):
    ...




class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0025_parameter'),
        ('analyzers_manager', '0016_params'),
        ('connectors_manager', '0015_params'),
        ('visualizers_manager', '0013_params'),
    ]

    operations = [

        migrations.AddField(
            model_name="pluginconfig",
            name="parameter",
            field=models.ForeignKey("api_app.parameter",default=None,  on_delete=django.db.models.deletion.CASCADE, null=True,
                                    related_name="values"),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="for_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="value",
            field=models.JSONField(blank=True, null=True)
        ),
        migrations.RunPython(
            migrate_plugin_config, reverse_migrate_plugin_config
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="parameter",
            field=models.ForeignKey("api_app.parameter",  on_delete=django.db.models.deletion.CASCADE,
                                    null=False,
                                    related_name="values"),
        ),
        migrations.RemoveConstraint(
            model_name='pluginconfig',
            name='unique_custom_config_entry',
        ),
        migrations.RemoveField(
            model_name="pluginconfig",
            name="organization"
        ),
        migrations.RemoveField(
            model_name="pluginconfig",
            name="plugin_name"
        ),
        migrations.RemoveField(
            model_name="pluginconfig",
            name="attribute"
        ),
        migrations.RemoveField(
            model_name="pluginconfig",
            name="type"
        ),
        migrations.RemoveField(
            model_name="pluginconfig",
            name="config_type"
        ),
        migrations.AlterUniqueTogether(
            name="pluginconfig",
            unique_together={("owner", "for_organization", "parameter")}
        ),
        migrations.RemoveIndex(
            model_name='pluginconfig',
            name='api_app_plu_owner_i_ff141f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pluginconfig',
            name='api_app_plu_type_92301a_idx',
        )
    ]
