# Generated by Django 4.1.7 on 2023-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0028_plugin_config'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['analyzer_config', 'is_secret'], name='api_app_par_analyze_1f1bee_idx'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['connector_config', 'is_secret'], name='api_app_par_connect_a49bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['visualizer_config', 'is_secret'], name='api_app_par_visuali_99f678_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginconfig',
            index=models.Index(fields=['owner', 'for_organization', 'parameter'], name='api_app_plu_owner_i_55ca9b_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginconfig',
            index=models.Index(fields=['owner', 'for_organization'], name='api_app_plu_owner_i_c6658a_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginconfig',
            index=models.Index(fields=['owner'], name='api_app_plu_owner_i_691c79_idx'),
        ),
    ]
