# Generated by Django 4.1.7 on 2023-04-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0028_plugin_config'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pluginconfig',
            name='api_app_plu_organiz_0867bd_idx',
        ),
    ]
