# Generated by Django 4.1.9 on 2023-06-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0030_pluginconfig_repositories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('analyzers_complete', 'analyzers_complete'), ('connectors_complete', 'connectors_complete'), ('visualizers_complete', 'visualizers_complete'), ('reported_without_fails', 'reported_without_fails'), ('reported_with_fails', 'reported_with_fails'), ('killed', 'killed'), ('failed', 'failed')], default='pending', max_length=32),
        ),
    ]
