# Generated by Django 4.1.9 on 2023-06-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0031_job_playbookconfigordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("running", "running"),
                    ("analyzers_running", "analyzers_running"),
                    ("connectors_running", "connectors_running"),
                    ("visualizers_running", "visualizers_running"),
                    ("analyzers_completed", "analyzers_completed"),
                    ("connectors_completed", "connectors_completed"),
                    ("visualizers_completed", "visualizers_completed"),
                    ("reported_without_fails", "reported_without_fails"),
                    ("reported_with_fails", "reported_with_fails"),
                    ("killed", "killed"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
