# Generated by Django 4.1.10 on 2023-07-28 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0031_alter_analyzerconfig_name"),
        ("connectors_manager", "0018_alter_connectorconfig_name"),
        ("ingestors_manager", "0001_initial"),
        ("visualizers_manager", "0023_alter_visualizerconfig_name"),
        ("api_app", "0035_pluginconfig_repositories"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parameter",
            unique_together={
                ("name", "visualizer_config"),
                ("name", "analyzer_config"),
                ("name", "connector_config"),
            },
        ),
        migrations.AddField(
            model_name="parameter",
            name="ingestor_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="ingestors_manager.ingestorconfig",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parameter",
            unique_together={
                ("name", "visualizer_config"),
                ("name", "ingestor_config"),
                ("name", "analyzer_config"),
                ("name", "connector_config"),
            },
        ),
        migrations.AddIndex(
            model_name="parameter",
            index=models.Index(
                fields=["ingestor_config", "is_secret"],
                name="api_app_par_ingesto_517684_idx",
            ),
        ),
    ]
