# Generated by Django 4.1.10 on 2023-08-22 12:36
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0038_python_module_datamigration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameter",
            name="analyzer_config",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="connector_config",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="ingestor_config",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="visualizer_config",
        ),
        migrations.AlterField(
            model_name="parameter",
            name="python_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parameters",
                to="api_app.pythonmodule",
            ),
        ),
    ]
