# Generated by Django 4.1.10 on 2023-09-14 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api_app",
            "0046_remove_pluginconfig_plugin_config_no_config_all_null_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pythonmodule",
            options={"ordering": ["base_path", "module"]},
        ),
    ]
