# Generated by Django 4.1.10 on 2023-10-16 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0047_alter_pythonmodule_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="warnings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=900),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
