# Generated by Django 4.1.10 on 2023-10-02 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_app", "0048_job_warnings"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pluginconfig",
            name="api_app_plu_owner_i_691c79_idx",
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
