# Generated by Django 4.1.10 on 2023-11-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("api_app", "0050_python_module_update_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonmodule",
            name="health_check_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="healthcheck_for_%(class)s",
                to="django_celery_beat.crontabschedule",
            ),
        ),
    ]
