# Generated by Django 4.2.8 on 2024-01-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0052_periodic_task_bi"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="sent_to_bi",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
