# Generated by Django 4.2.8 on 2024-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0053_job_sent_to_bi"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["sent_to_bi", "-received_request_time"], name="JobBISearch"
            ),
        ),
    ]
