# Generated by Django 4.2.8 on 2024-01-09 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api_app", "0055_organizationpluginconfiguration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationpluginconfiguration",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__endswith": "config",
                    "app_label__endswith": "manager",
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
