# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models

def migrate(apps, schema_editor):
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    name = VisualizerConfig.objects.filter(name=models.OuterRef("old_visualizer_config")).values_list("pk")[:1]
    PluginConfig.objects.update(
        visualizer_config=models.Subquery(name)
    )
    Job = apps.get_model("api_app", "Job")
    for job in Job.objects.all():
        vcs = VisualizerConfig.objects.filter(name__in=job.visualizers_to_execute2)
        acs = AnalyzerConfig.objects.filter(name__in=job.analyzers_to_execute2)
        acs_requested = AnalyzerConfig.objects.filter(name__in=job.analyzers_requested2)
        ccs = ConnectorConfig.objects.filter(name__in=job.connectors_to_execute2)
        ccs_requested = ConnectorConfig.objects.filter(name__in=job.connectors_requested2)
        job.visualizers_to_execute.set(vcs)
        job.analyzers_to_execute.set(acs)
        job.analyzers_requested.set(acs_requested)
        job.connectors_to_execute.set(ccs)
        job.connectors_requested.set(ccs_requested)


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_3_change_primary_key"),
        ("analyzers_manager", "0058_3_change_primary_key"),
        ("connectors_manager", "0029_3_change_primary_key"),
        ("api_app", "0057_2_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pluginconfig",
            old_name="visualizer_config",
            new_name="old_visualizer_config"
        ),
        migrations.RenameField(
            model_name="pluginconfig",
            old_name="analyzer_config",
            new_name="old_analyzer_config"
        ),
        migrations.RenameField(
            model_name="pluginconfig",
            old_name="connector_config",
            new_name="old_connector_config"
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="visualizer_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="visualizers_manager.visualizerconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="analyzer_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="analyzers_manager.analyzerconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="connector_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="connectors_manager.connectorconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="visualizers_to_execute",
            field=models.ManyToManyField(
                blank=True,
                related_name="executed_in_jobs",
                to="visualizers_manager.VisualizerConfig",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="analyzers_to_execute",
            field=models.ManyToManyField(
                blank=True,
                related_name="executed_in_jobs",
                to="analyzers_manager.AnalyzerConfig",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="analyzers_requested",
            field=models.ManyToManyField(
                blank=True,
                related_name="requested_in_jobs",
                to="analyzers_manager.AnalyzerConfig",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="connectors_to_execute",
            field=models.ManyToManyField(
                blank=True,
                related_name="executed_in_jobs",
                to="connectors_manager.ConnectorConfig",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="connectors_requested",
            field=models.ManyToManyField(
                blank=True,
                related_name="requested_in_jobs",
                to="connectors_manager.ConnectorConfig",
            ),
        ),
        migrations.RunPython(
            migrate,
        ),
        migrations.RemoveField(
            model_name="pluginconfig",
            name="old_visualizer_config"
        ),
        migrations.RemoveField(
            model_name='pluginconfig',
            name='old_analyzer_config',
        ),
        migrations.RemoveField(
            model_name='pluginconfig',
            name='old_connector_config',
        ),
        migrations.RemoveField(
            model_name="job",
            name="visualizers_to_execute2"
        ),
        migrations.RemoveField(
            model_name="job",
            name="analyzers_to_execute2"
        ),
        migrations.RemoveField(
            model_name="job",
            name="analyzers_requested2"
        ),
        migrations.RemoveField(
            model_name="job",
            name="connectors_to_execute2"
        ),
        migrations.RemoveField(
            model_name="job",
            name="connectors_requested2"
        )

    ]
