# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.contrib.postgres.fields
from django.contrib.postgres.expressions import ArraySubquery
from django.db import migrations, models


def migrate(apps, schema_editor):
    Job = apps.get_model("api_app", "Job")
    Job.objects.update(
        visualizers_to_execute2=ArraySubquery(
            Job.objects.filter(pk=models.OuterRef("pk")).values(
                "visualizers_to_execute__name"
            )
        ),
        analyzers_to_execute2=ArraySubquery(
            Job.objects.filter(pk=models.OuterRef("pk")).values(
                "analyzers_to_execute__name"
            )
        ),
        analyzers_requested2=ArraySubquery(
            Job.objects.filter(pk=models.OuterRef("pk")).values(
                "analyzers_requested__name"
            )
        ),
        connectors_to_execute2=ArraySubquery(
            Job.objects.filter(pk=models.OuterRef("pk")).values(
                "connectors_to_execute__name"
            )
        ),
        connectors_requested2=ArraySubquery(
            Job.objects.filter(pk=models.OuterRef("pk")).values(
                "connectors_requested__name"
            )
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_1_change_primary_key"),
        ("analyzers_manager", "0058_1_change_primary_key"),
        ("connectors_manager", "0029_1_change_primary_key"),
        ("ingestors_manager", "0016_1_change_primary_key"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginconfig",
            name="visualizer_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="analyzer_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="connector_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="ingestor_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="visualizers_to_execute2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="analyzers_to_execute2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="analyzers_requested2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="connectors_to_execute2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="connectors_requested2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(
            model_name="job",
            name="visualizers_to_execute",
        ),
        migrations.RemoveField(
            model_name="job",
            name="analyzers_to_execute",
        ),
        migrations.RemoveField(
            model_name="job",
            name="analyzers_requested",
        ),
        migrations.RemoveField(
            model_name="job",
            name="connectors_to_execute",
        ),
        migrations.RemoveField(
            model_name="job",
            name="connectors_requested",
        ),
    ]
