# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_1_change_primary_key"),
        ("analyzers_manager", "0058_1_change_primary_key"),
        ("connectors_manager", "0029_1_change_primary_key"),
        ("ingestors_manager", "0016_1_change_primary_key"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginconfig",
            name="visualizer_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="analyzer_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="connector_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="pluginconfig",
            name="ingestor_config",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
