# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models

def migrate(apps, schema_editor):
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    VisualizerConfig = apps.get_model("visualizers_manager", "VisualizerConfig")
    name = VisualizerConfig.objects.filter(name=models.OuterRef("old_visualizer_config")).values_list("pk")[:1]
    PluginConfig.objects.update(
        visualizer_config=models.Subquery(name)
    )
    Job = apps.get_model("api_app", "Job")
    for job in Job.objects.all():
        vcs = VisualizerConfig.objects.filter(name__in=job.visualizers_to_execute2)
        job.visualizers_to_execute.set(vcs)


class Migration(migrations.Migration):
    dependencies = [
        ("visualizers_manager", "0036_3_change_primary_key"),
        ("api_app", "0057_2_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pluginconfig",
            old_name="visualizer_config",
            new_name="old_visualizer_config"
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="visualizer_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="visualizers_manager.visualizerconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="visualizers_to_execute",
            field=models.ManyToManyField(
                blank=True,
                related_name="executed_in_jobs",
                to="visualizers_manager.VisualizerConfig",
            ),
        ),
        migrations.RunPython(
            migrate,
        ),
        migrations.RemoveField(
            model_name="pluginconfig",
            name="old_visualizer_config"
        ),
        migrations.RemoveField(
            model_name="job",
            name="visualizers_to_execute2"
        )
    ]
