# Generated by Django 4.2.8 on 2024-01-09 14:31
import django
from django.db import migrations, models


def migrate(apps, schema_editor):
    Job = apps.get_model("api_app", "Job")
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    Job.objects.update(
        playbook_to_execute=models.Subquery(
            PlaybookConfig.objects.filter(
                name=models.OuterRef("old_playbook_to_execute")
            ).values_list("pk")[:1]
        ),
        playbook_requested=models.Subquery(
            PlaybookConfig.objects.filter(
                name=models.OuterRef("old_playbook_requested")
            ).values_list("pk")[:1]
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0024_3_change_primary_key"),
        ("api_app", "0058_2_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="playbook_requested",
            new_name="old_playbook_requested",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="playbook_to_execute",
            new_name="old_playbook_to_execute",
        ),
        migrations.AddField(
            model_name="job",
            name="playbook_to_execute",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executed_in_jobs",
                to="playbooks_manager.playbookconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="playbook_requested",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_in_jobs",
                to="playbooks_manager.playbookconfig",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(model_name="job", name="old_playbook_requested"),
        migrations.RemoveField(model_name="job", name="old_playbook_to_execute"),
    ]
