# Generated by Django 4.2.8 on 2024-01-19 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certego_saas_organization", "0002_membership_is_admin"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("api_app", "0058_4_change_primary_key"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationpluginconfiguration",
            unique_together={("object_id", "organization", "content_type")},
        ),
    ]
