# Generated by Django 4.2.8 on 2024-01-30 14:31

from django.db import migrations, models


def migrate(apps, schema_editor):
    Job = apps.get_model("api_app", "Job")
    last_root = Job.objects.order_by("pk").first()
    if last_root:
        last_root.path = last_root._get_path(None, 1, 1)
        last_root.save()
        for job in Job.objects.exclude(pk=last_root.pk).order_by("pk"):
            newpath = last_root._inc_path()
            job.path = newpath
            job.save()
            last_root = job


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0059_alter_organizationpluginconfiguration_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="depth",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="path",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="job",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
