# Generated by Django 4.2.8 on 2024-01-30 14:31
from django.db import migrations, models
from django.db.models import CharField, F, Value
from django.db.models.functions import Concat


def migrate(apps, schema_editor):
    # I have to use the import here because i really need the class methods
    from api_app.models import Job as JobNonStoric

    PivotMap = apps.get_model("pivots_manager", "PivotMap")
    Analysis = apps.get_model("analyses_manager", "Analysis")

    # we are now setting all the children
    for obj in PivotMap.objects.all():
        parent = obj.starting_job  # parent
        child = obj.ending_job
        parent.numchild += 1
        parent.save()
        child.depth = 2
        child.path = JobNonStoric._get_path(parent.path, child.depth, 1)
        child.save()
        an = Analysis.objects.create(
            name="Pivot analysis",
            owner=parent.user,
            start_time=parent.received_request_time,
            end_time=child.finished_analysis_time,
            status="concluded",
        )
        an.jobs.add(parent)

    Analysis.objects.update(
        name=Concat(F("name"), Value(" #"), F("pk"), output_field=CharField())
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0060_job_depth_job_numchild_job_path"),
        ("pivots_manager", "0025_alter_pivotmap_ending_job"),
        ("analyses_manager", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(migrate, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="job",
                    name="path",
                    field=models.CharField(max_length=255, unique=True),
                ),
            ],
        )
    ]
