# Generated by Django 4.2.8 on 2024-02-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses_manager", "0001_initial"),
        ("api_app", "0060_job_depth_job_numchild_job_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="analyses_manager.analysis",
            ),
        ),
    ]
