# Generated by Django 4.2.11 on 2024-03-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0061_job_depth_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="python_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="api_app.pythonmodule",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
