# Generated by Django 4.2.15 on 2024-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0062_alter_parameter_python_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastElasticReportUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update_datetime", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="lastelasticreportupdate",
            constraint=models.CheckConstraint(
                check=models.Q(("pk", 1)),
                name="singleton",
                violation_error_message="This class is a singleton: only one object is allowed",
            ),
        ),
    ]
