# Generated by Django 4.2.16 on 2024-12-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0064_vt_sample_download"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["depth", "path", "id"], name="MPNodeSearch"),
        ),
    ]
