# Generated by Django 4.2.17 on 2025-01-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api_app", "0065_job_mpnodesearch"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lastelasticreportupdate",
            name="singleton",
        ),
        migrations.AddField(
            model_name="job",
            name="data_model_content_type",
            field=models.ForeignKey(
                editable=False,
                limit_choices_to={"app_label": "data_model_manager"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="data_model_object_id",
            field=models.IntegerField(editable=False, null=True, blank=True),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["data_model_content_type", "data_model_object_id"],
                name="api_app_job_data_mo_8b5e5f_idx",
            ),
        ),
    ]
