# Generated by Django 4.2.17 on 2025-01-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api_app", "0067_add_analyzable"),
        ("analyzables_manager", "0002_migrate_data"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="api_app_job_md5_4d2c5e_idx",
        ),
        migrations.RemoveField(
            model_name="job",
            name="file",
        ),
        migrations.RemoveField(
            model_name="job",
            name="file_mimetype",
        ),
        migrations.RemoveField(
            model_name="job",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_sample",
        ),
        migrations.RemoveField(
            model_name="job",
            name="md5",
        ),
        migrations.RemoveField(
            model_name="job",
            name="observable_classification",
        ),
        migrations.RemoveField(
            model_name="job",
            name="observable_name",
        ),
        migrations.AlterField(
            model_name="job",
            name="analyzable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="analyzables_manager.analyzable",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="api_app_job_status_27bc7f_idx"),
        ),
    ]
