# Generated by Django 4.2.17 on 2025-01-23 14:38

import django.db.models.deletion
from django.db import migrations, models


def migrate(apps, schema_editor):
    Comment = apps.get_model("api_app", "Comment")
    for comment in Comment.objects.all():
        comment.analyzable = comment.job.analyzable
        comment.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "analyzables_manager",
            "0003_analyzable_analyzables_classif_adf7ca_idx_and_more",
        ),
        ("api_app", "0068_remove_job_api_app_job_md5_4d2c5e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="analyzable",
            field=models.ForeignKey(
                null=True,
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="analyzables_manager.analyzable",
            ),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
