# Generated by Django 4.2.17 on 2025-01-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analyzables_manager",
            "0003_analyzable_analyzables_classif_adf7ca_idx_and_more",
        ),
        ("api_app", "0069_remove_comment_job_comment_analyzable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="job",
        ),
        migrations.AlterField(
            model_name="comment",
            name="analyzable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="analyzables_manager.analyzable",
            ),
        ),
    ]
