# Generated by Django 4.2.17 on 2025-01-28 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations_manager', '0001_initial'),
        ('api_app', '0070_remove_comment_job_comment_analyzable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='investigation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='investigations_manager.investigation'),
        ),
    ]
