# Generated by Django 4.2.27 on 2026-01-21 10:38
# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

from django.db import migrations


def add_hibp_analyzers(apps, schema_editor):
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    PythonModule = apps.get_model("api_app", "PythonModule")
    Parameter = apps.get_model("api_app", "Parameter")
    PluginConfig = apps.get_model("api_app", "PluginConfig")

    # Create PythonModule for passwords
    python_module_passwords, _ = PythonModule.objects.update_or_create(
        module="hibp_passwords",
        base_path="api_app.analyzers_manager.observable_analyzers",
        defaults={
            "update_schedule": None,
            "health_check_schedule": None,
        },
    )

    # Create PythonModule for breaches
    python_module_breaches, _ = PythonModule.objects.update_or_create(
        module="hibp_breaches",
        base_path="api_app.analyzers_manager.observable_analyzers",
        defaults={
            "update_schedule": None,
            "health_check_schedule": None,
        },
    )

    # HibpPasswords - only generic
    AnalyzerConfig.objects.update_or_create(
        name="HibpPasswords",
        defaults={
            "type": "observable",
            "description": (
                "Analyzer for HaveIBeenPwned pwned passwords (k-anonymity). "  # noqa: E501
                "Supports: generic (password string). No API key required."
            ),
            "python_module": python_module_passwords,
            "observable_supported": ["generic"],
            "soft_time_limit": 30,
            "supported_filetypes": [],
            "run_hash": False,
            "disabled": False,
        },
    )

    # HibpBreaches - generic and domain
    hibp_breaches_config, _ = AnalyzerConfig.objects.update_or_create(
        name="HibpBreaches",
        defaults={
            "type": "observable",
            "description": (
                "Analyzer for HaveIBeenPwned breaches (emails and domains). "
                "Supports: generic (email), domain. Requires API key."
            ),
            "python_module": python_module_breaches,
            "observable_supported": ["generic", "domain"],
            "soft_time_limit": 30,
            "supported_filetypes": [],
            "run_hash": False,
            "disabled": False,
        },
    )

    # For HibpBreaches: Create API key parameter
    api_key_param, _ = Parameter.objects.update_or_create(
        name="api_key_name",
        python_module=python_module_breaches,
        defaults={
            "type": "string",
            "description": "HIBP API key for authenticated endpoints",
            "is_secret": True,
            "required": True,
        },
    )

    # Set default test key via PluginConfig
    PluginConfig.objects.update_or_create(
        parameter=api_key_param,
        analyzer_config=hibp_breaches_config,
        defaults={
            "value": "00000000000000000000000000000000",
        },
    )


def reverse_add_hibp_analyzers(apps, schema_editor):
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    PythonModule = apps.get_model("api_app", "PythonModule")
    Parameter = apps.get_model("api_app", "Parameter")
    PluginConfig = apps.get_model("api_app", "PluginConfig")

    AnalyzerConfig.objects.filter(
        name__in=["HibpPasswords", "HibpBreaches"]
    ).delete()  # noqa: E501
    PythonModule.objects.filter(
        module__in=["hibp_passwords", "hibp_breaches"]
    ).delete()  # noqa: E501
    Parameter.objects.filter(name="api_key_name").delete()
    PluginConfig.objects.filter(parameter__name="api_key_name").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0071_delete_last_elastic_report"),
    ]

    operations = [
        migrations.RunPython(
            add_hibp_analyzers,
            reverse_add_hibp_analyzers,
        ),
    ]
