# Generated by Django 4.2.16 on 2024-11-08 09:38

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import api_app.data_model_manager.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IETFReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rrname",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        max_length=100
                    ),
                ),
                (
                    "rrtype",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        max_length=100
                    ),
                ),
                (
                    "rdata",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        size=None,
                    ),
                ),
                ("time_first", models.DateTimeField()),
                ("time_last", models.DateTimeField()),
            ],
            options={
                "unique_together": {("rrname", "rrtype", "rdata")},
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        max_length=100
                    ),
                ),
                ("url", models.URLField(blank=True, default=None, null=True)),
                ("score", models.PositiveIntegerField(default=0)),
                ("signature", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="IPDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "external_references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "related_threats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "malware_family",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("additional_info", models.JSONField(default=dict)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("asn", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "asn_rank",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("certificates", models.JSONField(blank=True, default=None, null=True)),
                (
                    "org_name",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "country_code",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "registered_country_code",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "isp",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "resolutions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), default=list, size=None
                    ),
                ),
                (
                    "ietf_report",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ips",
                        to="data_model_manager.ietfreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "external_references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "related_threats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "malware_family",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("additional_info", models.JSONField(default=dict)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "comments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("file_information", models.JSONField(blank=True, default=dict)),
                ("stats", models.JSONField(blank=True, default=dict)),
                (
                    "signatures",
                    models.ManyToManyField(
                        related_name="files", to="data_model_manager.signature"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomainDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "external_references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "related_threats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=api_app.data_model_manager.fields.LowercaseCharField(
                            max_length=100
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "malware_family",
                    api_app.data_model_manager.fields.LowercaseCharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("additional_info", models.JSONField(default=dict)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("rank", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "ietf_report",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="data_model_manager.ietfreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
