# Generated by Django 4.2.15 on 2024-10-14 07:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_model_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedatamodel",
            name="additional_info",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="basedatamodel",
            name="evaluation",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="basedatamodel",
            name="malware_family",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="basedatamodel",
            name="related_threats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="basedatamodel",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="domaindatamodel",
            name="ietf_report",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_model_manager.ietfreport",
            ),
        ),
        migrations.AlterField(
            model_name="domaindatamodel",
            name="rank",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="filedatamodel",
            name="comments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="filedatamodel",
            name="file_information",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="filedatamodel",
            name="stats",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="asn",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="asn_rank",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="certificates",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="country",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="country_code",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="ietf_report",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_model_manager.ietfreport",
            ),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="isp",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="org_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="registered_country",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ipdatamodel",
            name="registered_country_code",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
