# Generated by Django 4.2.16 on 2024-11-08 11:42

import django.contrib.postgres.fields
from django.db import migrations, models

import api_app.data_model_manager.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_model_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaindatamodel",
            name="resolutions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=api_app.data_model_manager.fields.LowercaseCharField(
                    max_length=100
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.RemoveField(
            model_name="domaindatamodel",
            name="ietf_report",
        ),
        migrations.AddField(
            model_name="domaindatamodel",
            name="ietf_report",
            field=models.ManyToManyField(
                related_name="domains", to="data_model_manager.ietfreport"
            ),
        ),
    ]
