# Generated by Django 4.2.16 on 2024-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_model_manager", "0002_domaindatamodel_resolutions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipdatamodel",
            name="ietf_report",
        ),
        migrations.AddField(
            model_name="ipdatamodel",
            name="ietf_report",
            field=models.ManyToManyField(
                related_name="ips", to="data_model_manager.ietfreport"
            ),
        ),
    ]
