# Generated by Django 4.2.16 on 2024-12-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_model_manager",
            "0005_alter_domaindatamodel_external_references_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
