# Generated by Django 4.2.16 on 2024-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_model_manager",
            "0005_alter_domaindatamodel_external_references_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipdatamodel",
            name="asn_rank",
            field=models.DecimalField(
                blank=True, decimal_places=20, default=None, max_digits=21, null=True
            ),
        ),
    ]
