# Generated by Django 4.2.17 on 2025-03-13 10:11

from django.db import migrations

import api_app.data_model_manager.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_model_manager", "0009_alter_domaindatamodel_evaluation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaindatamodel",
            name="kill_chain_phase",
            field=api_app.data_model_manager.fields.LowercaseCharField(
                blank=True,
                choices=[
                    ("reconnaissance", "Reconnaissance"),
                    ("weaponization", "Weaponization"),
                    ("delivery", "Delivery"),
                    ("exploitation", "Exploitation"),
                    ("installation", "Installation"),
                    ("c2", "C2"),
                    ("action", "Action"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filedatamodel",
            name="kill_chain_phase",
            field=api_app.data_model_manager.fields.LowercaseCharField(
                blank=True,
                choices=[
                    ("reconnaissance", "Reconnaissance"),
                    ("weaponization", "Weaponization"),
                    ("delivery", "Delivery"),
                    ("exploitation", "Exploitation"),
                    ("installation", "Installation"),
                    ("c2", "C2"),
                    ("action", "Action"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ipdatamodel",
            name="kill_chain_phase",
            field=api_app.data_model_manager.fields.LowercaseCharField(
                blank=True,
                choices=[
                    ("reconnaissance", "Reconnaissance"),
                    ("weaponization", "Weaponization"),
                    ("delivery", "Delivery"),
                    ("exploitation", "Exploitation"),
                    ("installation", "Installation"),
                    ("c2", "C2"),
                    ("action", "Action"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
