# Generated by Django 4.2.17 on 2025-10-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_model_manager", "0010_domaindatamodel_killchain_phase_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="domaindatamodel",
            index=models.Index(fields=["date"], name="data_model__date_42dc17_idx"),
        ),
        migrations.AddIndex(
            model_name="filedatamodel",
            index=models.Index(fields=["date"], name="data_model__date_b1234c_idx"),
        ),
        migrations.AddIndex(
            model_name="ipdatamodel",
            index=models.Index(fields=["date"], name="data_model__date_48d248_idx"),
        ),
    ]
