# IMPORTANT: The version must match the version of docker-compose.yml
---
# All additional integrations should be added following this format only.

services:
  phishing_analyzers:
    build:
      context: ../integrations/phishing_analyzers
      dockerfile: Dockerfile
    image: intelowlproject/intelowl_phishing_analyzers:test
