# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-03-09 10:38

from django.db import migrations, models


def migrate(apps, schema_editor):
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    for config in AnalyzerConfig.objects.all():
        if config.external_service:
            config.maximum_tlp = "AMBER"
        if config.leaks_info:
            config.maximum_tlp = "GREEN"
        config.save()


def backwards_migrate(apps, schema_editor):
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    for config in AnalyzerConfig.objects.all():
        if config.maximum_tlp == "RED":
            config.external_service = False
            config.leaks_info = False
        elif config.maximum_tlp == "AMBER":
            config.external_service = True
            config.leaks_info = False
        elif config.maximum_tlp in ["GREEN", "CLEAR"]:
            config.leaks_info = True
            config.external_service = True
        config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0009_parent_playbook_foreign_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerconfig",
            name="maximum_tlp",
            field=models.CharField(
                choices=[
                    ("CLEAR", "Clear"),
                    ("GREEN", "Green"),
                    ("AMBER", "Amber"),
                    ("RED", "Red"),
                ],
                default="RED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analyzerconfig",
            name="leaks_info",
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(migrate, backwards_migrate),
        migrations.RemoveField(
            model_name="analyzerconfig",
            name="leaks_info",
        ),
        migrations.RemoveField(
            model_name="analyzerconfig",
            name="external_service",
        ),
    ]
