# Generated by Django 3.2.4 on 2021-06-17 08:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analyzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "analyzer_type",
                    models.CharField(
                        choices=[
                            ("file_analyzer", "file_analyzer"),
                            ("observable_analyzer", "observable_analyzer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("disabled", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("python_module", models.CharField(max_length=128)),
                (
                    "supported_filetypes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default=list, max_length=50
                        ),
                        size=None,
                    ),
                ),
                (
                    "not_supported_filetypes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default=list, max_length=50
                        ),
                        size=None,
                    ),
                ),
                ("run_hash", models.BooleanField(default=False)),
                (
                    "run_hash_type",
                    models.CharField(
                        blank=True,
                        choices=[("md5", "md5"), ("sha256", "sha256")],
                        default="md5",
                        max_length=50,
                    ),
                ),
                (
                    "observable_supported",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default=list, max_length=50
                        ),
                        size=None,
                    ),
                ),
                ("leaks_info", models.BooleanField(default=False)),
                ("external_service", models.BooleanField(default=False)),
                (
                    "queue",
                    models.CharField(
                        choices=[
                            ("default", "default"),
                            ("long", "long"),
                            ("local", "local"),
                        ],
                        default="default",
                        max_length=50,
                    ),
                ),
                ("soft_time_limit", models.PositiveIntegerField(default=300)),
                (
                    "additional_config_params",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("env_variable_key", models.CharField(max_length=50)),
                (
                    "datatype",
                    models.CharField(
                        choices=[
                            ("str", "str"),
                            ("int", "int"),
                            ("bool", "bool"),
                            ("float", "float"),
                        ],
                        max_length=8,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("default", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField()),
                (
                    "analyzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="analyzers_manager.analyzer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalyzerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("failed", "failed"),
                            ("success", "success"),
                        ],
                        max_length=50,
                    ),
                ),
                ("report", models.JSONField(default=dict)),
                (
                    "errors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default=list, max_length=512
                        ),
                        size=None,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "analyzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="analyzers_manager.analyzer",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyzer_reports",
                        to="api_app.job",
                    ),
                ),
            ],
        ),
    ]
