# Generated by Django 3.2.4 on 2021-07-06 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzerreport",
            name="errors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
