# Generated by Django 3.2.14 on 2022-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='parent_playbook',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
