# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.14 on 2022-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerreport",
            name="parent_playbook",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
