# Generated by Django 3.2.18 on 2023-02-22 13:53

import django.contrib.postgres.fields
from django.db import migrations, models

import api_app.core.models
import api_app.fields
import api_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0002_analyzerreport_parent_playbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerConfig',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('file', 'File'), ('observable', 'Observable')], max_length=50)),
                ('python_module', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('disabled', models.BooleanField()),
                ('config', models.JSONField(default=api_app.core.models.config_default, validators=[api_app.validators.validate_config])),
                ('secrets', models.JSONField(blank=True, default=dict, validators=[api_app.validators.validate_secrets])),
                ('params', models.JSONField(blank=True, default=dict, validators=[api_app.validators.validate_params])),
                ('docker_based', models.BooleanField(default=False)),
                ('external_service', models.BooleanField(default=True)),
                ('leaks_info', models.BooleanField()),
                ('observable_supported', api_app.fields.ChoiceArrayField(base_field=models.CharField(choices=[('ip', 'Ip'), ('url', 'Url'), ('domain', 'Domain'), ('hash', 'Hash'), ('generic', 'Generic')], max_length=30), blank=True, default=list, size=None)),
                ('supported_filetypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), blank=True, default=list, size=None)),
                ('run_hash', models.BooleanField(default=False)),
                ('run_hash_type', models.CharField(blank=True, choices=[('md5', 'Md5'), ('sha256', 'Sha256')], max_length=10)),
                ('not_supported_filetypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
