# Generated by Django 3.2.4 on 2021-07-06 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0002_alter_analyzerreport_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzerreport",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="analyzerreport",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
