# Generated by Django 3.2.14 on 2022-09-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0002_analyzerreport_parent_playbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzerreport",
            name="parent_playbook",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
