# Generated by Django 3.2.4 on 2021-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0003_auto_20210706_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerreport",
            name="runtime_configuration",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
