# Generated by Django 3.2.4 on 2021-07-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analyzers_manager", "0006_alter_analyzerreport_status")]

    operations = [
        migrations.AddField(
            model_name="analyzerreport",
            name="task_id",
            field=models.UUIDField(default="1ba0e330-9786-4928-b89d-b1fbef72b9c1"),
            preserve_default=False,
        )
    ]
