# Generated by Django 3.2.18 on 2023-03-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_mitm_configs'),
        ('analyzers_manager', '0006_analyzerconfig_disabled_in_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzerreport',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzerreports', to='api_app.job'),
        ),
    ]
