# Generated by Django 4.1.7 on 2023-04-05 15:22

import django.db.models.deletion
from django.core.exceptions import ValidationError
from django.db import migrations, models

import api_app.fields

def create_config(configs, type:str, Parameter,PluginConfig):
    for config in configs:
        for param_name, param_values in config.params.items():
            param = Parameter(analyzer_config=config, name=param_name, type=param_values["type"], description=param_values["description"], is_secret=False, required=param_values.get("required", False))
            try:
                param.full_clean()
            except ValidationError:
                Parameter.objects.get(name=param_name, type=param_values["type"], is_secret=False)
            else:
                param.save()

            if "default" in param_values:
                if param_values["default"] is None and param_values["type"] == "str":
                    param_values["default"] = ""
                PluginConfig.objects.get_or_create(
                    owner=None,
                    value=param_values["default"],
                    plugin_name=config.name,
                    attribute=param_name,
                    type=type,
                    config_type="1"
                )
        for secret_name, secret_values in config.secrets.items():
            secret = Parameter(analyzer_config=config, name=secret_name, type=secret_values["type"],
                                                       description=secret_values["description"], is_secret=True, required=secret_values["required"])
            try:
                secret.full_clean()
            except ValidationError:
                Parameter.objects.get(name=secret_name, type=secret_values["type"],
                                              is_secret=True)
            else:
                secret.save()

            if "default" in secret_values:
                PluginConfig.objects.get_or_create(
                    owner=None,
                    value=secret_values["default"],
                    plugin_name=config.name,
                    attribute=secret_name,
                    type=type,
                    config_type="2"
                )
        config.save()


def migrate(apps, schema_editor):
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    Parameter = apps.get_model("api_app", "Parameter")
    ParameterConfig = apps.get_model("api_app", "ParameterConfig")
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    create_config(list(AnalyzerConfig.objects.all()), "1", Parameter, ParameterConfig, PluginConfig)

def reverse_migrate(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0022_otx_check_hash_timeout'),
        ('api_app', '0027_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerconfig",
            name="parameters",
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_configurations',
                                         to='api_app.parameterconfig'),

        ),
        migrations.RunPython(
            migrate, reverse_migrate
        ),
        migrations.RemoveField(
            model_name="analyzerconfig",
            name="params"
        ),
        migrations.RemoveField(
            model_name="analyzerconfig",
            name="secrets"
        )

    ]
