# Generated by Django 4.1.10 on 2023-08-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0037_pythonmodule_and_more"),
        (
            "analyzers_manager",
            "0038_rename_analyzers_m_python__3e6166_idx_analyzers_m_python__657cda_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerconfig",
            name="python_module2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api_app.pythonmodule",
                null=True,
            ),
        ),
    ]
