# Generated by Django 4.1.10 on 2023-08-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0039_remove_fields"),
        ("analyzers_manager", "0039_alter_analyzerconfig_python_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyzerconfig",
            name="python_module",
        ),
        migrations.RenameField(
            model_name="analyzerconfig",
            old_name="python_module2",
            new_name="python_module",
        ),
    ]
