# Generated by Django 4.1.10 on 2023-08-22 12:36
import json

from django.db import migrations


def migrate(apps, schema_editor):
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    PythonModule = apps.get_model("api_app", "PythonModule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    for task in PeriodicTask.objects.filter(task="intel_owl.tasks.update"):
        kwargs = json.loads(task.kwargs)
        try:
            config = AnalyzerConfig.objects.get(pk=kwargs["config_pk"])
        except KeyError:
            kwargs["python_module_pk"] = PythonModule.objects.get(
                module=kwargs["python_module_pk"],
                base_path__in=[
                    "api_app.analyzers_manager.observable_analyzers",
                    "api_app.analyzers_manager.file_analyzers",
                ],
            ).pk
        else:
            kwargs["python_module_pk"] = config.python_module2.pk
        task.kwargs = json.dumps(kwargs)
        task.save()


def reverse_migrate(apps, schema_editor):
    ...


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0039_remove_fields"),
        ("analyzers_manager", "0039_alter_analyzerconfig_python_module"),
    ]

    operations = [
        migrations.RunPython(migrate, reverse_migrate),
        migrations.RemoveField(
            model_name="analyzerconfig",
            name="python_module",
        ),
        migrations.RenameField(
            model_name="analyzerconfig",
            old_name="python_module2",
            new_name="python_module",
        ),
    ]
