# Generated by Django 4.1.10 on 2023-11-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0049_remove_analyzerconfig_update_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerconfig",
            name="health_check_status",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
