# Generated by Django 4.2.8 on 2023-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0054_analyzer_config_dns0_rrsets_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerreport",
            name="sent_to_bi",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
