# Generated by Django 4.2.8 on 2024-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0056_alter_analyzer_config_dns0_rrsets_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyzerreport",
            index=models.Index(
                fields=["sent_to_bi", "-start_time"], name="analyzerreportsBISearch"
            ),
        ),
    ]
