# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models

def migrate(apps, schema_editor):
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    id = 1
    for config in AnalyzerConfig.objects.all():
        config.id = id
        config.save()
        id += 1


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0057_analyzerreport_analyzerreportsbisearch"),
        ("playbooks_manager", "0022_add_dns0_to_free_playbook"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzerconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
                null=True,
                blank=True
            )
        ),
        migrations.RunPython(
            migrate
        ),
        migrations.AlterField(
            model_name="analyzerconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
            )
        ),
    ]
