# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models


def migrate(apps, schema_editor):
    AnalyzerReport = apps.get_model("analyzers_manager", "AnalyzerReport")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    name = AnalyzerConfig.objects.filter(
        name=models.OuterRef("old_config")
    ).values_list("pk")[:1]
    AnalyzerReport.objects.update(config=models.Subquery(name))


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0058_3_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyzerreport", old_name="config", new_name="old_config"
        ),
        migrations.AddField(
            model_name="analyzerreport",
            name="config",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="analyzers_manager.analyzerconfig",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate),
        migrations.AlterUniqueTogether(
            name="analyzerreport",
            unique_together={("config", "job")},
        ),
        migrations.RemoveField(model_name="analyzerreport", name="old_config"),
    ]
