# Generated by Django 4.2.11 on 2024-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0077_analyzer_config_abusix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzerconfig",
            name="health_check_status",
            field=models.BooleanField(default=True),
        ),
    ]
