# Generated by Django 4.2.15 on 2024-09-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0121_analyzer_config_guarddogobservable_go"),
        ("analyzers_manager", "0121_analyzer_config_guarddogobservable_npm"),
        ("analyzers_manager", "0121_analyzer_config_guarddogobservable_pypi"),
    ]

    operations = []
