# Generated by Django 4.2.15 on 2024-09-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0123_analyzer_config_guarddogfile_go"),
        ("analyzers_manager", "0123_analyzer_config_guarddogfile_npm"),
        ("analyzers_manager", "0123_analyzer_config_guarddogfile_pypi"),
    ]

    operations = []
