# Generated by Django 4.2.16 on 2024-11-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0131_analyzer_config_urldna_new_scan"),
        ("analyzers_manager", "0131_analyzer_config_urldna_search"),
    ]

    operations = []
