# Generated by Django 4.2.17 on 2025-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0146_analyzer_config_wad"),
    ]

    operations = [
        migrations.CreateModel(
            name="JA4Fingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("library", models.CharField(blank=True, max_length=255, null=True)),
                ("device", models.CharField(blank=True, max_length=255, null=True)),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent_string", models.TextField(blank=True, null=True)),
                (
                    "certificate_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("observation_count", models.PositiveIntegerField(default=1)),
                ("verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "ja4_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ja4_fingerprint_string", models.TextField(blank=True, null=True)),
                (
                    "ja4s_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ja4h_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ja4x_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ja4t_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ja4ts_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ja4tscan_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
