# Generated by Django 4.2.17 on 2025-02-21 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0071_delete_last_elastic_report"),
        ("analyzers_manager", "0151_analyzer_config_ipquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorExitAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("ip", models.GenericIPAddressField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrancoRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0)),
                ("rank", models.IntegerField()),
                ("domain", models.CharField(max_length=512)),
                (
                    "retrieved_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "unique_together": {("rank", "domain", "retrieved_date")},
            },
        ),
        migrations.CreateModel(
            name="FireHolRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=1)),
                ("file_date", models.DateTimeField()),
                ("source", models.CharField(max_length=300)),
                ("ip_start", models.GenericIPAddressField()),
                ("ip_end", models.GenericIPAddressField()),
                ("category", models.CharField(max_length=300)),
            ],
            options={
                "unique_together": {("source", "ip_start", "ip_end", "category")},
            },
        ),
        migrations.CreateModel(
            name="AnalyzerSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=512)),
                ("file", models.FileField(upload_to="analyzers_source_files")),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "python_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="api_app.pythonmodule",
                    ),
                ),
            ],
            options={
                "unique_together": {("file_name", "python_module")},
            },
        ),
    ]
