# Generated by Django 4.2.17 on 2025-06-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    def migrate(apps, schema_editor):
        PythonModule = apps.get_model("api_app", "PythonModule")
        Parameter = apps.get_model("api_app", "Parameter")
        pm = PythonModule.objects.get(
            module="greedybear.GreedyBear",
            base_path="api_app.analyzers_manager.observable_analyzers",
        )
        p1 = Parameter(
            name="command_sequence_toggle",
            type="bool",
            description="Enable fetching details from CommandSequenceAPI. Enabled by default, if sha256 hash is provided",
            is_secret=False,
            required=True,
            python_module=pm,
        )
        p2 = Parameter(
            name="same_cluster_commands",
            type="bool",
            description="Enable fetching details from CommandSequenceAPI for same cluster commands",
            is_secret=False,
            required=False,
            python_module=pm,
        )
        p1.full_clean()
        p1.save()

        p2.full_clean()
        p2.save()

    def reverse_migrate(apps, schema_editor):
        PythonModule = apps.get_model("api_app", "PythonModule")
        Parameter = apps.get_model("api_app", "Parameter")
        pm = PythonModule.objects.get(
            module="greedybear.GreedyBear",
            base_path="api_app.analyzers_manager.observable_analyzers",
        )
        p1 = Parameter.objects.get(name="command_sequence_toggle", python_module=pm)
        p2 = Parameter.objects.get(name="same_cluster_commands", python_module=pm)
        p1.delete()
        p2.delete()

    dependencies = [
        ("analyzers_manager", "0157_analyzer_config_phunter"),
    ]

    operations = [migrations.RunPython(migrate, reverse_migrate)]
