# Generated by Django 4.2.17 on 2025-06-21 17:29

from django.db import migrations


def migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    Parameter = apps.get_model("api_app", "Parameter")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    pm = PythonModule.objects.get(
        module="greedybear.GreedyBear",
        base_path="api_app.analyzers_manager.observable_analyzers",
    )
    AnalyzerConfig.objects.filter(python_module=pm).update(
        description="Scan an IP, domain or a command sequence hash against the [GreedyBear](https://www.honeynet.org/2021/12/27/new-project-available-greedybear/) service",
        observable_supported=["ip", "domain", "hash"],
    )
    p1 = Parameter(
        name="command_sequence_toggle",
        type="bool",
        description="Enable fetching details from CommandSequenceAPI. Enabled by default if sha-256 hash is provided",
        is_secret=False,
        required=False,
        python_module=pm,
    )
    p2 = Parameter(
        name="same_cluster_commands",
        type="bool",
        description="Enable fetching details from CommandSequenceAPI for same cluster commands. Disabled by default",
        is_secret=False,
        required=False,
        python_module=pm,
    )

    p1.full_clean()
    p1.save()

    p2.full_clean()
    p2.save()


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0159_analyzer_config_expandurl"),
    ]
    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
