# Generated by Django 4.2.17 on 2025-09-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0071_delete_last_elastic_report"),
        ("analyzers_manager", "0166_analyzer_config_yarax"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzerRulesFileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_downloaded_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("download_url", models.URLField(blank=True, default="")),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "python_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules_version",
                        to="api_app.pythonmodule",
                    ),
                ),
            ],
        ),
    ]
