# Generated by Django 4.2.17 on 2025-07-24 14:57

from django.db import migrations


def migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    Parameter = apps.get_model("api_app", "Parameter")
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")

    pm = PythonModule.objects.get(
        module="capa_info.CapaInfo",
        base_path="api_app.analyzers_manager.file_analyzers",
    )

    new_crontab, created = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="0",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )
    if created:
        pm.update_schedule = new_crontab
        pm.full_clean()
        pm.save()

    AnalyzerConfig.objects.filter(python_module=pm).update(soft_time_limit=1800)
    AnalyzerConfig.objects.filter(python_module=pm).update(docker_based=False)

    p1 = Parameter(
        name="timeout",
        type="float",
        description="Duration in seconds for which intelowl waits for capa to return results. Default is set to 15 seconds.",
        is_secret=False,
        required=False,
        python_module=pm,
    )

    p2 = Parameter(
        name="force_pull_signatures",
        type="bool",
        description="Force download signatures from flare-capa github repository",
        is_secret=False,
        required=False,
        python_module=pm,
    )

    p1.full_clean()
    p1.save()

    p2.full_clean()
    p2.save()

    analyzer_configs = AnalyzerConfig.objects.filter(python_module=pm)

    plugin_config_to_create = [
        PluginConfig(analyzer_config=config, parameter=p1, value=15)
        for config in analyzer_configs
    ]

    PluginConfig.objects.bulk_create(plugin_config_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0167_analyzerrulesfileversion"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
