# Generated by Django 4.2.25 on 2025-11-03 10:37

from django.db import migrations


def migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")

    guarddog_file_module = PythonModule.objects.get(
        module="guarddog_file.GuardDogFile",
        base_path="api_app.analyzers_manager.file_analyzers",
    )

    guarddog_generic_module = PythonModule.objects.get(
        module="guarddog_generic.GuardDogGeneric",
        base_path="api_app.analyzers_manager.observable_analyzers",
    )

    AnalyzerConfig.objects.filter(python_module=guarddog_file_module).update(
        disabled=True
    )
    AnalyzerConfig.objects.filter(python_module=guarddog_generic_module).update(
        disabled=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0168_update_capa"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
