# Generated by Django 4.2.27 on 2026-01-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0171_analyzer_config_hibpbreaches'),
        ('analyzers_manager', '0172_analyzer_config_hibppasswords'),
    ]

    operations = [
    ]
