# Generated by Django 4.2.27 on 2026-02-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0171_add_unprotect_yara_rules'),
        ('analyzers_manager', '0174_phishstats_url'),
    ]

    operations = [
    ]
