# Generated by Django 4.2 on 2025-03-03

from django.db import migrations


def migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    Parameter = apps.get_model("api_app", "Parameter")
    PluginConfig = apps.get_model("api_app", "PluginConfig")

    pm = PythonModule.objects.get(
        module="capa_info.CapaInfo",
        base_path="api_app.analyzers_manager.file_analyzers",
    )

    timeout_param = Parameter.objects.get(python_module=pm, name="timeout")
    timeout_param.description = (
        "Duration in seconds for which intelowl waits for capa to return results. Default is set to 120 seconds."
    )
    timeout_param.save()

    PluginConfig.objects.filter(parameter=timeout_param).update(value=120)


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0177_update_urlscan_observable_supported"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
