# Generated by Django 4.2.27 on 2026-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0182_add_local_db_models_tweetfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamhausDropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(db_index=True, max_length=10)),
                ('value', models.CharField(db_index=True, max_length=50)),
                ('network_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Spamhaus Drop Item',
                'verbose_name_plural': 'Spamhaus Drop Items',
                'unique_together': {('data_type', 'value')},
            },
        ),
    ]
