# Generated by Django 4.2.27 on 2026-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0183_spamhausdropitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StratosphereIPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('list_type', models.CharField(db_index=True, max_length=50)),
                ('rating', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Stratosphere IP Entry',
                'verbose_name_plural': 'Stratosphere IP Entries',
                'unique_together': {('ip', 'list_type')},
            },
        ),
    ]
