# Generated by Django 4.2.27 on 2026-03-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0184_stratosphereipentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireholIPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_name', models.CharField(db_index=True, max_length=50)),
                ('ip_or_subnet', models.CharField(db_index=True, max_length=50)),
                ('network_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'FireHol IP Entry',
                'verbose_name_plural': 'FireHol IP Entries',
                'unique_together': {('ip_or_subnet', 'list_name')},
            },
        ),
    ]
