# Generated by Django 4.2.27 on 2026-03-23 19:07

from django.db import migrations


def add_update_schedules(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    
    # daily crontab schedule (midnight every day)
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="0",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*"
    )
    
    modules_to_update = [
        {"module": "stratosphere.Stratos", "base_path": "api_app.analyzers_manager.observable_analyzers"},
        {"module": "firehol_iplist.FireHol_IPList", "base_path": "api_app.analyzers_manager.observable_analyzers"}
    ]
    
    for mod_data in modules_to_update:
        try:
            module = PythonModule.objects.get(**mod_data)
            module.update_schedule = schedule
            module.save()
        except PythonModule.DoesNotExist:
            pass


def remove_update_schedules(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    
    modules_to_update = [
        {"module": "stratosphere.Stratos", "base_path": "api_app.analyzers_manager.observable_analyzers"},
        {"module": "firehol_iplist.FireHol_IPList", "base_path": "api_app.analyzers_manager.observable_analyzers"}
    ]
    
    for mod_data in modules_to_update:
        try:
            module = PythonModule.objects.get(**mod_data)
            module.update_schedule = None
            module.save()
        except PythonModule.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0185_fireholipentry'),
    ]

    operations = [
        migrations.RunPython(add_update_schedules, reverse_code=remove_update_schedules),
    ]
