# Generated by Django 4.2.27 on 2026-03-25 17:05

from django.db import migrations


def update_capa_timeout(apps, schema_editor):
    Parameter = apps.get_model("api_app", "Parameter")
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    PythonModule = apps.get_model("api_app", "PythonModule")

    try:
        pm = PythonModule.objects.get(
            module="capa_info.CapaInfo",
            base_path="api_app.analyzers_manager.file_analyzers",
        )
        param = Parameter.objects.get(name="timeout", python_module=pm)
        PluginConfig.objects.filter(parameter=param, value=15).update(value=120)
    except (PythonModule.DoesNotExist, Parameter.DoesNotExist):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0186_add_update_schedule_stratosphere_firehol"),
    ]

    operations = [
        migrations.RunPython(update_capa_timeout, migrations.RunPython.noop),
    ]
