# Generated by Django 4.2.27 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0187_remove_dehashed_analyzer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ja4DBEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint_type", models.CharField(db_index=True, max_length=20)),
                ("fingerprint_value", models.CharField(db_index=True, max_length=1024)),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "JA4 DB Entry",
                "verbose_name_plural": "JA4 DB Entries",
            },
        ),
    ]
