# Generated by Django 4.2.27 on 2026-03-25 17:05

from django.db import migrations


def update_capa_timeout(apps, schema_editor):
    Parameter = apps.get_model("api_app", "Parameter")
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    PythonModule = apps.get_model("api_app", "PythonModule")

    try:
        pm = PythonModule.objects.get(
            module="capa_info.CapaInfo",
            base_path="api_app.analyzers_manager.file_analyzers",
        )
        param = Parameter.objects.get(name="timeout", python_module=pm)
        for config in PluginConfig.objects.filter(parameter=param):
            if config.value == 15:
                config.value = 120
                config.save(update_fields=["value"])

        description = getattr(param, "description", None)
        if description:
            new_description = description.replace("15", "120")
            if new_description != description:
                param.description = new_description
                param.save(update_fields=["description"])
    except (PythonModule.DoesNotExist, Parameter.DoesNotExist):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0187_remove_dehashed_analyzer"),
    ]

    operations = [
        migrations.RunPython(update_capa_timeout, migrations.RunPython.noop),
    ]
