# Generated by Django 4.2.27 on 2026-03-25 17:05

from django.db import migrations


def update_capa_timeout(apps, schema_editor):
    Parameter = apps.get_model("api_app", "Parameter")
    PluginConfig = apps.get_model("api_app", "PluginConfig")
    PythonModule = apps.get_model("api_app", "PythonModule")

    try:
        pm = PythonModule.objects.get(
            module="capa_info.CapaInfo",
            base_path="api_app.analyzers_manager.file_analyzers",
        )
        param = Parameter.objects.get(name="timeout", python_module=pm)
        import re

        PluginConfig.objects.filter(parameter=param, value__in=["15", 15]).update(value=120)

        description = getattr(param, "description", None)
        if description:
            new_description = re.sub(r"\b15\b", "120", description)
            if new_description != description:
                param.description = new_description
                param.save(update_fields=["description"])
    except (PythonModule.DoesNotExist, Parameter.DoesNotExist):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0188_ja4dbentry"),
    ]

    operations = [
        migrations.RunPython(update_capa_timeout, migrations.RunPython.noop),
    ]
