# Generated by Django 3.2.14 on 2022-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('connectors_manager', '0002_connectorreport_parent_playbook'), ('connectors_manager', '0003_alter_connectorreport_parent_playbook')]

    dependencies = [
        ('connectors_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorreport',
            name='parent_playbook',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
