# Generated by Django 3.2.4 on 2021-07-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("connectors_manager", "0002_auto_20210706_1212")]

    operations = [
        migrations.AlterField(
            model_name="connectorreport",
            name="connector",
            field=models.CharField(max_length=128),
        )
    ]
