# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-02-22 13:53

from django.db import migrations, models

import api_app.core.models
import api_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('connectors_manager', '0002_connectorreport_parent_playbook'),
        ('api_app', '0010_custom_config_playbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorConfig',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('python_module', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('disabled', models.BooleanField(default=False)),
                ('config', models.JSONField(default=api_app.core.models.config_default,
                                            validators=[api_app.validators.validate_config])),
                ('secrets',
                 models.JSONField(blank=True, default=dict, validators=[api_app.validators.validate_secrets])),
                ('params',
                 models.JSONField(blank=True, default=dict, validators=[api_app.validators.validate_params])),
                ('maximum_tlp', models.CharField(choices=[('WHITE', 'White'), ('GREEN', 'Green'), ('AMBER', 'Amber'), ('RED', 'Red')], default='WHITE', max_length=50)),
                ('run_on_failure', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]