# Generated by Django 3.2.14 on 2022-09-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors_manager', '0002_connectorreport_parent_playbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorreport',
            name='parent_playbook',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
