# Generated by Django 3.2.4 on 2021-07-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_remove_job_runtime_configuration'),
        ('connectors_manager', '0003_alter_connectorreport_connector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectorreport',
            unique_together={('connector', 'job')},
        ),
    ]
