# Generated by Django 3.2.4 on 2021-07-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0008_remove_job_runtime_configuration"),
        ("connectors_manager", "0004_alter_connectorreport_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connectorreport",
            old_name="connector",
            new_name="connector_name",
        ),
        migrations.AlterUniqueTogether(
            name="connectorreport", unique_together={("connector_name", "job")}
        ),
    ]
