# Generated by Django 3.2.4 on 2021-07-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("connectors_manager", "0005_auto_20210723_0557")]

    operations = [
        migrations.AlterField(
            model_name="connectorreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILED", "FAILED"),
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("SUCCESS", "SUCCESS"),
                    ("KILLED", "KILLED"),
                ],
                max_length=50,
            ),
        )
    ]
