# Generated by Django 3.2.18 on 2023-03-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_mitm_configs'),
        ('connectors_manager', '0006_connectorconfig_disabled_in_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorreport',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectorreports', to='api_app.job'),
        ),
    ]
