# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-03-08 16:23

import django.db.models.deletion
from django.db import migrations, models


def migrate(apps, schema_editor):
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    ConnectorReport = apps.get_model("connectors_manager", "ConnectorReport")
    for report in ConnectorReport.objects.all():
        report.config = ConnectorConfig.objects.get(name=report.name)
        report.save()

def backwards_migrate(apps, schema_editor):
    ConnectorReport = apps.get_model("connectors_manager", "ConnectorReport")
    for report in ConnectorReport.objects.all():
        report.name = report.config.name
        report.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_mitm_configs'),
        ('connectors_manager', '0007_alter_connectorreport_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorreport',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='connectors_manager.connectorconfig'),
        ),
        migrations.RunPython(
            migrate, backwards_migrate
        ),
        migrations.AlterField(
            model_name='connectorreport',
            name="config",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports',
                                    to='connectors_manager.connectorconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='connectorreport',
            unique_together={('config', 'job')},
        ),
        migrations.AlterField(
            model_name="connectorreport",
            name="name",
            field=models.CharField(max_length=50, primary_key=True, serialize=False, null=True),
        ),
        migrations.RemoveField(
            model_name='connectorreport',
            name='name',
        ),
    ]
