# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl
# See the file 'LICENSE' for copying permission.

# Generated by Django 3.2.18 on 2023-02-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors_manager', '0012_slack'),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectorconfig",
            name='maximum_tlp',
            field=models.CharField(choices=[
                ('WHITE', 'White'), ('GREEN', 'Green'), ('AMBER', 'Amber'), ('RED', 'Red')], default='CLEAR', max_length=50)

        )
    ]
