# Generated by Django 4.1.10 on 2023-08-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0037_pythonmodule_and_more"),
        ("connectors_manager", "0018_alter_connectorconfig_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="connectorconfig",
            new_name="connectors__python__f23fd8_idx",
            old_name="connectors__python__0fb146_idx",
        ),
        migrations.AddField(
            model_name="connectorconfig",
            name="python_module2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api_app.pythonmodule",
                null=True,
            ),
        ),
    ]
