# Generated by Django 4.1.10 on 2023-08-22 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0039_remove_fields"),
        (
            "connectors_manager",
            "0019_rename_connectors__python__0fb146_idx_connectors__python__f23fd8_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectorconfig",
            name="python_module",
        ),
        migrations.RenameField(
            model_name="connectorconfig",
            old_name="python_module2",
            new_name="python_module",
        ),
    ]
