# Generated by Django 4.1.10 on 2023-08-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0039_remove_fields'),
        ('connectors_manager', '0020_alter_python_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorconfig',
            name='python_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api_app.pythonmodule'),
        ),
    ]
