# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models

def migrate(apps, schema_editor):
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    id = 1
    for config in ConnectorConfig.objects.all():
        config.id = id
        config.save()
        id += 1


class Migration(migrations.Migration):
    dependencies = [
        ("connectors_manager", "0028_connectorreport_connectorreportsbisearch"),
        ("playbooks_manager", "0022_add_dns0_to_free_playbook"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
                null=True,
                blank=True
            )
        ),
        migrations.RunPython(
            migrate
        ),
        migrations.AlterField(
            model_name="connectorconfig",
            name="id",
            field=models.BigIntegerField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
                primary_key=False,
            )
        ),
    ]
