# Generated by Django 4.2.8 on 2024-01-09 14:31
import django
from django.db import migrations, models


def migrate(apps, schema_editor):
    ConnectorReport = apps.get_model("connectors_manager", "ConnectorReport")
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    name = ConnectorConfig.objects.filter(
        name=models.OuterRef("old_config")
    ).values_list("pk")[:1]
    ConnectorReport.objects.update(config=models.Subquery(name))
    for config in ConnectorConfig.objects.all():
        if config.disabled2:
            ContentType = apps.get_model("contenttypes", "ContentType")
            ct = ContentType.objects.get_for_model(config)
            OrganizationPluginConfiguration = apps.get_model(
                "api_app", "OrganizationPluginConfiguration"
            )
            for org in config.disabled2:
                if org:
                    OrganizationPluginConfiguration.objects.create(
                        organization=org,
                        object_id=config.pk,
                        content_type=ct,
                        disabled=True,
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
        ("connectors_manager", "0029_3_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connectorreport", old_name="config", new_name="old_config"
        ),
        migrations.AddField(
            model_name="connectorreport",
            name="config",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="connectors_manager.connectorconfig",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate),
        migrations.AlterUniqueTogether(
            name="connectorreport",
            unique_together={("config", "job")},
        ),
        migrations.RemoveField(model_name="connectorconfig", name="disabled2"),
        migrations.RemoveField(model_name="connectorreport", name="old_config"),
    ]
