# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connectors_manager", "0002_0003_connector_config_yeti"),
        ("playbooks_manager", "0001_initial_squashed"),
        ("api_app", "0001_2_initial_squashed"),
    ]

    operations = []
