# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models


def migrate(apps, schema_editor):
    ConnectorReport = apps.get_model("connectors_manager", "ConnectorReport")
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    name = ConnectorConfig.objects.filter(name=models.OuterRef("old_config")).values_list("pk")[:1]
    ConnectorReport.objects.update(
        config=models.Subquery(name)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("connectors_manager", "0029_3_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connectorreport",
            old_name="config",
            new_name="old_config"
        ),
        migrations.AddField(
            model_name="connectorreport",
            name="config",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="connectors_manager.connectorconfig",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate
        ),
        migrations.RemoveField(
            model_name="connectorreport",
            name="old_config"
        )
    ]
