{{- if and .Values.redis.enabled .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intelowl.fullname" . }}-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- if .Values.redis.auth.password }}
  password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
