# Generated by Django 4.1.9 on 2023-06-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0033_alter_parameter_unique_together"),
        (
            "pivots_manager",
            "0002_rename_pivot_manag_startin_21e74a_idx_pivots_mana_startin_694120_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pivot",
            name="ending_job",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pivot_parents",
                to="api_app.job",
            ),
        ),
        migrations.AlterField(
            model_name="pivot",
            name="starting_job",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pivot_children",
                to="api_app.job",
            ),
        ),
        migrations.AlterField(
            model_name="pivot",
            name="pivot_config",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pivots",
                to="pivots_manager.pivotconfig",
            ),
        ),
    ]
