# Generated by Django 4.1.10 on 2023-08-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0039_alter_analyzerconfig_python_module"),
        ("visualizers_manager", "0026_alter_visualizerconfig_python_module"),
        ("connectors_manager", "0021_alter_connectorconfig_python_module"),
        ("pivots_manager", "0005_pivotconfig_pivot_config_no_config_all_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pivotconfig",
            name="analyzer_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pivots",
                to="analyzers_manager.analyzerconfig",
            ),
        ),
        migrations.AlterField(
            model_name="pivotconfig",
            name="connector_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pivots",
                to="connectors_manager.connectorconfig",
            ),
        ),
        migrations.AlterField(
            model_name="pivotconfig",
            name="visualizer_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pivots",
                to="visualizers_manager.visualizerconfig",
            ),
        ),
    ]
