# Generated by Django 4.1.10 on 2023-09-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0047_alter_pythonmodule_options"),
        ("pivots_manager", "0009_alter_pivotconfig_python_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pivotconfig",
            name="execute_on_python_module",
            field=models.ForeignKey(
                limit_choices_to={
                    "base_path__in": [
                        "api_app.analyzers_manager.file_analyzers",
                        "api_app.analyzers_manager.observable_analyzers",
                        "api_app.connectors_manager.connectors",
                    ]
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pivots",
                to="api_app.pythonmodule",
            ),
        ),
    ]
