# Generated by Django 4.1.10 on 2023-09-14 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pivots_manager", "0010_alter_pivotconfig_execute_on_python_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pivotconfig",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$", "Your name should match the [A-Za-z0-9_] characters"
                    )
                ],
            ),
        ),
    ]
