# Generated by Django 4.1.10 on 2023-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pivots_manager", "0012_alter_pivotconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pivotconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("related_analyzer_config__isnull", False),
                    ("related_connector_config__isnull", False),
                    _connector="OR",
                ),
                name="pivot_config_no_null_configs",
            ),
        ),
    ]
