# Generated by Django 4.1.10 on 2023-09-18 13:12

from django.db import migrations


def migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    Parameter = apps.get_model("api_app", "Parameter")
    pm = PythonModule.objects.get(
        module="base.Base", base_path="api_app.pivots_manager.pivots"
    )
    pm.module = "compare.Compare"
    Parameter.objects.create(
        name="field_to_compare",
        type="str",
        description="Dotted path to the field",
        is_secret=False,
        required=True,
        python_module=pm,
    )
    pm.save()


def reverse_migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    pm = PythonModule.objects.get(
        module="compare.Compare", base_path="api_app.pivots_manager.pivots"
    )
    pm.module = "base.Base"
    pm.parameters.all().delete()
    pm.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pivots_manager", "0013_pivotconfig_pivot_config_no_null_configs"),
    ]

    operations = [
        migrations.RemoveField(model_name="pivotconfig", name="field_to_compare"),
        migrations.RunPython(migrate, reverse_migrate),
    ]
