# Generated by Django 4.1.10 on 2023-11-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("pivots_manager", "0017_pivotconfig_routing_key_pivotconfig_soft_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="pivotconfig",
            name="health_check_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="healthcheck_for_%(class)s",
                to="django_celery_beat.crontabschedule",
            ),
        ),
        migrations.AddField(
            model_name="pivotconfig",
            name="health_check_task",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="healthcheck_for_%(class)s",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="pivotconfig",
            name="update_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="update_for_%(class)s",
                to="django_celery_beat.crontabschedule",
            ),
        ),
        migrations.AddField(
            model_name="pivotconfig",
            name="update_task",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="update_for_%(class)s",
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
