# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.contrib.postgres.fields
from django.contrib.postgres.expressions import ArraySubquery
from django.db import migrations, models


def migrate(apps, schema_editor):
    PivotConfig = apps.get_model("pivots_manager", "PivotConfig")
    PivotConfig.objects.update(
        related_analyzer_configs2=ArraySubquery(
            PivotConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "related_analyzer_configs__name"
            )
        ),
        related_connector_configs2=ArraySubquery(
            PivotConfig.objects.filter(pk=models.OuterRef("pk")).values(
                "related_connector_configs__name"
            )
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0058_1_change_primary_key"),
        ("connectors_manager", "0029_1_change_primary_key"),
        ("pivots_manager", "0002_001_compare"),
    ]

    operations = [
        migrations.AddField(
            model_name="pivotconfig",
            name="related_analyzer_configs2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="pivotconfig",
            name="related_connector_configs2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate),
        migrations.RemoveField(
            model_name="pivotconfig",
            name="related_analyzer_configs",
        ),
        migrations.RemoveField(
            model_name="pivotconfig",
            name="related_connector_configs",
        ),
    ]
