# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations, models


def migrate(apps, schema_editor):
    PivotConfig = apps.get_model("pivots_manager", "PivotConfig")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")
    ConnectorConfig = apps.get_model("connectors_manager", "ConnectorConfig")
    for pivot in PivotConfig.objects.all():
        acs = AnalyzerConfig.objects.filter(
            name__in=pivot.related_analyzer_configs2
        ).values_list("pk", flat=True)
        ccs = ConnectorConfig.objects.filter(
            name__in=pivot.related_connector_configs2
        ).values_list("pk", flat=True)
        pivot.related_analyzer_configs.set(acs)
        pivot.related_connector_configs.set(ccs)


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers_manager", "0058_3_change_primary_key"),
        ("connectors_manager", "0029_3_change_primary_key"),
        ("pivots_manager", "0023_2_change_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="pivotconfig",
            name="related_analyzer_configs",
            field=models.ManyToManyField(
                blank=True,
                related_name="pivots",
                to="analyzers_manager.AnalyzerConfig",
            ),
        ),
        migrations.AddField(
            model_name="pivotconfig",
            name="related_connector_configs",
            field=models.ManyToManyField(
                blank=True,
                related_name="pivots",
                to="connectors_manager.ConnectorConfig",
            ),
        ),
        migrations.RunPython(
            migrate,
        ),
        migrations.RemoveField(
            model_name="pivotconfig", name="related_analyzer_configs2"
        ),
        migrations.RemoveField(
            model_name="pivotconfig", name="related_connector_configs2"
        ),
    ]
