# Generated by Django 4.2.8 on 2024-01-09 14:31
import django.core.validators
from django.db import migrations, models


def migrate(apps, schema_editor):
    PivotConfig = apps.get_model("pivots_manager", "PivotConfig")
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    PivotConfig.objects.update(
        playbook_to_execute=models.Subquery(
            PlaybookConfig.objects.filter(
                name=models.OuterRef("old_playbook_to_execute")
            ).values_list("pk")[:1]
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0024_3_change_primary_key"),
        ("pivots_manager", "0024_2_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pivotconfig",
            old_name="playbook_to_execute",
            new_name="old_playbook_to_execute",
        ),
        migrations.AddField(
            model_name="pivotconfig",
            name="playbook_to_execute",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pivots",
                to="playbooks_manager.playbookconfig",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate,
        ),
        migrations.RemoveField(
            model_name="pivotconfig", name="old_playbook_to_execute"
        ),
    ]
