# Generated by Django 4.2.11 on 2024-07-09 07:50

from django.db import migrations, models


def migrate(apps, schema_editor):
    PivotConfig = apps.get_model("pivots_manager", "PivotConfig")
    for pivot in PivotConfig.objects.all():
        pivot.playbooks_choice.set([pivot.playbook_to_execute])
        pivot.save()


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0050_add_goresym_to_sample_static_abalysis"),
        ("pivots_manager", "0030_pivot_config_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="pivotconfig",
            name="playbooks_choice",
            field=models.ManyToManyField(
                related_name="executed_by_pivots", to="playbooks_manager.playbookconfig"
            ),
        ),
        migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop),
    ]
