# Generated by Django 4.2.11 on 2024-07-09 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pivots_manager", "0031_remove_pivotconfig_playbook_to_execute_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pivotconfig",
            name="playbook_to_execute",
        ),
    ]
