# Generated by Django 4.2.17 on 2025-01-22 08:59

from django.db import migrations, models
from django.utils.timezone import now

import api_app.defaults


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analyzable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("md5", models.CharField(max_length=255, unique=True, editable=False)),
                (
                    "sha256",
                    models.CharField(max_length=255, unique=True, editable=False),
                ),
                ("sha1", models.CharField(max_length=255, unique=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "mimetype",
                    models.CharField(
                        blank=True, max_length=80, null=True, default=None
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True,
                        default=None,
                        blank=True,
                        upload_to=api_app.defaults.file_directory_path,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        max_length=100,
                        choices=[
                            ("ip", "Ip"),
                            ("url", "Url"),
                            ("domain", "Domain"),
                            ("hash", "Hash"),
                            ("generic", "Generic"),
                            ("file", "File"),
                        ],
                    ),
                ),
                ("discovery_date", models.DateTimeField(default=now)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
