# Generated by Django 4.2.17 on 2025-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzables_manager", "0002_migrate_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyzable",
            index=models.Index(
                fields=["classification"], name="analyzables_classif_adf7ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyzable",
            index=models.Index(
                fields=["mimetype"], name="analyzables_mimetyp_321d7d_idx"
            ),
        ),
    ]
