# Generated by Django 4.2.17 on 2025-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analyzables_manager",
            "0003_analyzable_analyzables_classif_adf7ca_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyzable",
            index=models.Index(fields=["name"], name="analyzables_name_aa34aa_idx"),
        ),
    ]
