# Generated by Django 4.2.8 on 2024-02-08 11:11

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import api_app.interfaces


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_app", "0001_1_initial_squashed"),
        ("playbooks_manager", "0001_initial_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestorConfig",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\w+$",
                                "Your name should "
                                "match the ["
                                "A-Za-z0-9_] "
                                "characters",
                            )
                        ],
                    ),
                ),
                (
                    "python_module",
                    models.ForeignKey(
                        limit_choices_to={
                            "base_path": "api_app.ingestors_manager.ingestors"
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="api_app.pythonmodule",
                    ),
                ),
                ("description", models.TextField()),
                ("disabled", models.BooleanField(default=False)),
                (
                    "health_check_status",
                    models.BooleanField(default=True, editable=False),
                ),
                (
                    "health_check_task",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="healthcheck_for_%(class)s",
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "soft_time_limit",
                    models.IntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("routing_key", models.CharField(default="default", max_length=50)),
                (
                    "periodic_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestor",
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "playbook_to_execute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestors",
                        to="playbooks_manager.playbookconfig",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestors",
                        to="django_celery_beat.crontabschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("maximum_jobs", models.IntegerField(default=10)),
            ],
            options={"abstract": False, "ordering": ["name", "disabled"]},
            bases=(models.Model, api_app.interfaces.CreateJobsFromPlaybookInterface),
        ),
        migrations.AddIndex(
            model_name="ingestorconfig",
            index=models.Index(
                fields=["python_module", "disabled"],
                name="ingestors_m_python__5c8ce0_idx",
            ),
        ),
        migrations.RenameIndex(
            model_name="ingestorconfig",
            new_name="ingestors_m_python__b7a859_idx",
            old_name="ingestors_m_python__5c8ce0_idx",
        ),
        migrations.CreateModel(
            name="IngestorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("KILLED", "Killed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("report", models.JSONField(default=list, validators=[])),
                (
                    "errors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("task_id", models.UUIDField(null=True, blank=True)),
                (
                    "config",
                    models.ForeignKey(
                        "IngestorConfig",
                        related_name="reports",
                        on_delete=models.CASCADE,
                    ),
                ),
                (
                    "max_size_report",
                    models.IntegerField(default=None, null=True, blank=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        "api_app.Job",
                        related_name="%(class)ss",
                        on_delete=models.SET_NULL,
                        null=True,
                        blank=True,
                    ),
                ),
                ("sent_to_bi", models.BooleanField(default=False, editable=False)),
                ("parameters", models.JSONField(default={}, editable=False)),
            ],
        ),
        migrations.AddIndex(
            model_name="ingestorreport",
            index=models.Index(
                fields=["sent_to_bi", "-start_time"], name="ingestorreportsBISearch"
            ),
        ),
        migrations.AlterModelOptions(
            name="ingestorreport",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterField(
            model_name="ingestorreport",
            name="parameters",
            field=models.JSONField(editable=False),
        ),
    ]
