# Generated by Django 4.1.10 on 2023-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestors_manager", "0003_ingestor_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestorreport",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
