# Generated by Django 4.1.10 on 2023-08-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0037_pythonmodule_and_more"),
        ("ingestors_manager", "0004_alter_ingestorreport_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ingestorconfig",
            new_name="ingestors_m_python__b7a859_idx",
            old_name="ingestors_m_python__5c8ce0_idx",
        ),
        migrations.AddField(
            model_name="ingestorconfig",
            name="python_module2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api_app.pythonmodule",
                null=True,
            ),
        ),
    ]
