# Generated by Django 4.1.10 on 2023-09-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api_app",
            "0046_remove_pluginconfig_plugin_config_no_config_all_null_and_more",
        ),
        ("ingestors_manager", "0007_alter_ingestorconfig_python_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestorconfig",
            name="python_module",
            field=models.ForeignKey(
                limit_choices_to={"base_path": "api_app.ingestors_manager.ingestors"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api_app.pythonmodule",
            ),
        ),
    ]
