# Generated by Django 4.1.10 on 2023-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestors_manager", "0008_alter_ingestorconfig_python_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestorconfig",
            name="maximum_jobs",
            field=models.IntegerField(default=10),
        ),
    ]
