# Generated by Django 4.1.10 on 2023-11-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestors_manager", "0011_ingestorconfig_health_check_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestorconfig",
            name="health_check_status",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
