# Generated by Django 4.2.8 on 2023-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestors_manager", "0013_ingestorreport_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestorreport",
            name="sent_to_bi",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
