# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingestors_manager", "0015_ingestorreport_ingestorreportsbisearch"),
        ("playbooks_manager", "0022_add_dns0_to_free_playbook"),
        ("api_app", "0056_alter_organizationpluginconfiguration_content_type"),
    ]

    operations = []
