# Generated by Django 4.2.8 on 2024-01-09 14:31
import django
from django.db import migrations, models


def migrate(apps, schema_editor):
    IngestorConfig = apps.get_model("ingestors_manager", "IngestorConfig")
    PlaybookConfig = apps.get_model("playbooks_manager", "PlaybookConfig")
    IngestorConfig.objects.update(
        playbook_to_execute=models.Subquery(
            PlaybookConfig.objects.filter(
                name=models.OuterRef("old_playbook_to_execute")
            ).values_list("pk")[:1]
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0024_3_change_primary_key"),
        ("ingestors_manager", "0017_2_change_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingestorconfig",
            old_name="playbook_to_execute",
            new_name="old_playbook_to_execute",
        ),
        migrations.AddField(
            model_name="ingestorconfig",
            name="playbook_to_execute",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingestors",
                to="playbooks_manager.playbookconfig",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate,
        ),
        migrations.AlterField(
            model_name="ingestorconfig",
            name="playbook_to_execute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingestors",
                to="playbooks_manager.playbookconfig",
            ),
        ),
        migrations.RemoveField(
            model_name="ingestorconfig", name="old_playbook_to_execute"
        ),
    ]
