# Generated by Django 4.2.8 on 2024-01-09 14:31
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0024_1_change_primary_key"),
        ("ingestors_manager", "0016_4_change_primary_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestorconfig",
            name="playbook_to_execute",
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
