# Generated by Django 4.2.11 on 2024-04-09 15:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestors_manager", "0017_4_change_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestorconfig",
            name="delay",
            field=models.DurationField(
                default=datetime.timedelta,
                help_text="Expects data in the format 'DD HH:MM:SS'",
            ),
        ),
    ]
