# Generated by Django 4.2.11 on 2024-07-09 07:50

from django.db import migrations, models


def migrate(apps, schema_editor):
    IngestorConfig = apps.get_model("ingestors_manager", "IngestorConfig")
    for ingestor in IngestorConfig.objects.all():
        ingestor.playbooks_choice.set([ingestor.playbook_to_execute])
        ingestor.save()


class Migration(migrations.Migration):
    dependencies = [
        ("playbooks_manager", "0050_add_goresym_to_sample_static_abalysis"),
        ("ingestors_manager", "0022_ingestor_fix_duplicated_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestorconfig",
            name="playbooks_choice",
            field=models.ManyToManyField(
                related_name="ingestors", to="playbooks_manager.playbookconfig"
            ),
        ),
        migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop),
    ]
