name: "Tag stale issues and pull requests"

on:
  schedule:
    - cron: "0 9 * * *" # Runs every day at 9 AM
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ github.token }}
        stale-pr-message: "This pull request has been marked as stale because it has had no activity for 10 days. If you are still working on this, please provide some updates or it will be closed in 5 days."
        close-pr-message: "This pull request has been closed because it had no updates in 15 days. If you're still working on this fell free to reopen."
        days-before-pr-stale: 10
        days-before-pr-close: 5
        stale-pr-label: "stale"
        exempt-pr-labels: "keep-open"
        operations-per-run: 100
        debug-only: false
        exempt-all-milestones: true