# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '3'

# All additional integrations should be added following this format only.

services:
  qiling:
    image: intelowlproject/intelowl_qiling:${INTELOWL_TAG_VERSION}
    container_name: intelowl_qiling
    restart: unless-stopped
    expose:
      - "4005"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intel_owl
      - ../integrations/qiling/rootfs:/opt/deploy/rootfs
      - ../integrations/qiling/profiles:/opt/deploy/profiles
    depends_on:
      - uwsgi
